### ISSUE TITLE
Search box issue and few suggestions

### ISSUE THREAD

**Issue by y2crow** [cschneegans/unattend-generator#101]
**Issue**
Tweak "Choose how to display the search box in the taskbar" always active, even if not changed it still creates script in XML.

**Suggestions** 
1. Windows Defender automatically turns on after some time. You can modify your 'Disable Windows Defender' system tweak adding the DisableAntiSpyware Group Policy, this Policy requires disabled Tamper Protection, this can also be done using the reg add command.
`reg.exe add "HKLM\SOFTWARE\Microsoft\Windows Defender\Features" /v TamperProtection /t REG_DWORD /d 4 /f`
`reg.exe add "HKLM\SOFTWARE\Microsoft\Windows Defender\Features" /v TamperProtectionSource /t REG_DWORD /d 2 /f`
`reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /t REG_DWORD /d 1 /f`
You can also disable Defender autologgers:
`reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\DefenderAuditLogger" /v Start /t REG_DWORD /d 0 /f`
`reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\DefenderApiLogger" /v Start /t REG_DWORD /d 0 /f`

2. Turn off "Windows Malicious Software Removal Tool" updates and reports. 
`reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v DontReportInfectionInformation /t REG_DWORD /d 1 /f`
`reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v DontOfferThroughWUAU /t REG_DWORD /d 1 /f`

3. Disable "Reserved Storage".
https://techcommunity.microsoft.com/t5/storage-at-microsoft/windows-10-and-reserved-storage/ba-p/428327
`reg.exe add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\ReserveManager" /v ShippedWithReserves /t REG_DWORD /d 0 /f`

4. Explorer pins:
Unpin "Home":
`reg.exe add "HKLM\SOFTWARE\Classes\CLSID\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}" /v System.IsPinnedToNamespaceTree /t REG_DWORD /d 0 /f`
`reg.exe add "HKLM\SOFTWARE\Classes\WOW6432Node\CLSID\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}" /v System.IsPinnedToNamespaceTree /t REG_DWORD /d 0 /f`
Unpin "Gallery":
`reg.exe add "HKLM\SOFTWARE\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}" /v System.IsPinnedToNamespaceTree /t REG_DWORD /d 0 /f`
`reg.exe add "HKLM\SOFTWARE\Classes\WOW6432Node\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}" /v System.IsPinnedToNamespaceTree /t REG_DWORD /d 0 /f`

**Comment by cschneegans** [comment]
> Tweak "Choose how to display the search box in the taskbar" always active, even if not changed it still creates script in XML.

Your observation is correct; the PowerShell statement that sets the `SearchboxTaskbarMode` registry value is always executed,  whenever a user logs on for the first time:

https://github.com/cschneegans/unattend-generator/blob/69ea92ecca109e6f7f7651001f0d1d6eaf3697e2/modifier/Optimizations.cs#L479

The default value in the form (_Show search box_) corresponds to the default behavior of both Windows 10 and 11, so if you keep the form's default values, Windows will render the search box as if the `SearchboxTaskbarMode` registry value would not have been set. I am not quite sure why you think this is a problem?

(JFTR, the setting was introduced in #59.)

**Comment by cschneegans** [comment]
> Windows Defender automatically turns on after some time.

I have never observed this. In fact, one of my computers was installed using an autounattend.xml file several months ago, and Windows Defender is still disabled:

```
PS C:\> Get-Process -Name 'msmpeng'
Get-Process : Cannot find a process with the name "msmpeng". Verify the process name and call the cmdlet again.

PS C:\> Get-Service -Name 'Sense', 'WdBoot', 'WdFilter', 'WdNisDrv', 'WdNisSvc', 'WinDefend' | Format-Table -AutoSize -Property StartType, Status, Name

StartType  Status Name
---------  ------ ----
 Disabled Stopped Sense
 Disabled Stopped WdBoot
 Disabled Stopped WdFilter
 Disabled Stopped WdNisDrv
 Disabled Stopped WdNisSvc
 Disabled Stopped WinDefend
```

**Comment by cschneegans** [comment]
> Your observation is correct; the PowerShell statement that sets the `SearchboxTaskbarMode` registry value is always executed

I have received further complaints about this behavior. Therefore, https://github.com/cschneegans/unattend-generator/commit/ea5e718fddcfbdd85079c0214ac8947b60b80e41 modifies the behavior so that the `SearchboxTaskbarMode` registry value is only set when it is different from its implicit default.

This means that when you use the [form's](https://schneegans.de/windows/unattend-generator/) default values, no `UserOnce.ps1` script will be emitted, and no PowerShell window will pop up every time a user logs on for the first time.
