### ISSUE TITLE
[REQUEST] Add option to disable HPET, intergrade NET Framework 2.0, 3.0 & 3.5 and disable Content Delivery Manager. Please

### ISSUE THREAD

**Issue by qewr4498** [cschneegans/unattend-generator#102]
If it already exist, pls tell me where 🙏 
& add option to enable end task in taskbar option (23h2 and 24h2) sry bad eng
thank u

**Comment by cschneegans** [comment]
• There already is a setting **Disable app suggestions**, and I have now added the term **Content Delivery Manager** to its description:

![image](https://github.com/user-attachments/assets/c0b6f71a-4d24-4525-b822-46f5c2887d24)

• To enable .NET Framework 3.5, please run
```
Enable-WindowsOptionalFeature -Online -FeatureName 'NetFx3';
```
as a .ps1 script in the _Scripts to run in the system context, before user accounts are created_ section. I don't think a dedicated setting is justified for this.

• I am not a gamer, and I have no experience with these HPET settings. As far as I understand, running `bcdedit.exe /deletevalue {current} useplatformclock` is supposed to disable HPET. Microsoft [warns](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set) that both `useplatformtick` and `useplatformclock` “should only be used for debugging”. Testing is also difficult for me as VMware guests apparently do not support HPET. I would assume that there are more specialized tools to optimize a Windows PC for gaming.

**Comment by qewr4498** [comment]
Add this please.
[HKEY_USERS\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings]
"TaskbarEndTask"=dword:00000001

**Comment by johnw41** [comment]
To enable .NET Framework 3.5, please run
> 
> ```
> Enable-WindowsOptionalFeature -Online -FeatureName 'NetFx3';
> ```
> 
> as a .ps1 script in the _Scripts to run in the system context, before user accounts are created_ section. I don't think a dedicated setting is justified for this.
 
This script run but not enable it in my windows (Win11_24H2). 
Is possible with this command and how? 
Dism.exe /online /enable-feature /featurename:NetFX3 /source:D:\sources\sxs /LimitAccess

**Comment by cschneegans** [comment]
> This script run but not enable it in my windows (Win11_24H2).

Thanks for pointing this out! Running `Enable-WindowsOptionalFeature -Online -FeatureName 'NetFx3'` in the _Scripts to run in the system context, before user accounts are created_ section indeed throws an error. To check the output of custom scripts, find the log files that match the `C:\Windows\Setup\Scripts\unattend-*.log` pattern:

```
Enable-WindowsOptionalFeature : Enable-WindowsOptionalFeature failed. Error code = 0x8024004a
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName 'NetFx3';
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```
 
However, running in the same script in the _Scripts to run when the first user logs on after Windows has been installed_ section succeeds, and .NET Framework 3.5 is properly installed.

**Comment by johnw41** [comment]
Thanks for the answer. Not enable also with this way. But working with this one 
"Scripts to run when the first user logs on after Windows has been installed" 
Dism /online /enable-feature /featurename:NetFX3 /source:D:\sources\sxs /LimitAccess
as cmd file.

**Comment by cschneegans** [comment]
> [HKEY_USERS\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings]
> "TaskbarEndTask"=dword:00000001

Is this really that important? I have never missed the _End task_ command, since _Close window_ does the same thing in almost all cases.
