### ISSUE TITLE
Question: Works for Server Versions? Can it remove unnecessary stuff?

### ISSUE THREAD

**Issue by FSquant** [cschneegans/unattend-generator#103]
Hi,

does the tool work for Windows Server Versions as well? 

Can it remove all that garbage:
- XBox / Games / Videos / Fotos / Camera
- unnecessary services excluded and not installed at all?

Regards

**Comment by cschneegans** [comment]
The autounattend.xml process in general and the autounattend.xml files generated by my service in particular do work with Windows 10 and 11 Server/Enterprise editions, yes.

Bloatware removal will almost certainly work as well.

The form also offers a setting to disable Windows Defender services. To stop or disable other services, you need to add custom scripts in the _Scripts to run in the system context, before user accounts are created_ section and call `sc.exe` or `Set-Service`.
