### ISSUE TITLE
Problem with double quotes and variables

### ISSUE THREAD

**Issue by hoang-himself** [cschneegans/unattend-generator#104]
The script has been working great, but recently I tested with IoT LTSC 2021 and 24H2 in Hyper-V and got `An expression was expected after '('`.
I found that the outer double quotes were causing the variable `$xml` to be expanded.

I don't know why but I only got this error recently. Is there any chance we can swap single and double quotes?

https://github.com/cschneegans/unattend-generator/blob/39732fd9d4f7e46df64b2b098a87bbd46bcea38c/Main.cs#L987

**Comment by cschneegans** [comment]
The code is correct, and there is certainly no issue with double or single quotes here. If the autounattend.xml file does not work as expected, there must be another reason.

When you run the
```
powershell.exe -NoProfile -Command "$xml = [xml]::new(); $xml.Load('C:\Windows\Panther\unattend.xml'); $sb = [scriptblock]::Create( $xml.unattend.Extensions.ExtractScript ); Invoke-Command -ScriptBlock $sb -ArgumentList $xml;"
```
command in PowerShell, you will indeed get an error:

![image](https://github.com/user-attachments/assets/85069b54-d189-48ac-ab4d-9764c99461f1)

But this is not how Windows Setup runs this command. To test the command properly, run it via the Windows _Run_ dialog (Windows key+R). You probably should add the `-NoExit` switch to keep the PowerShell window open so you can read any error messages:

```
powershell.exe -NoExit -NoProfile -Command "$xml = [xml]::new(); $xml.Load('C:\Windows\Panther\unattend.xml'); $sb = [scriptblock]::Create( $xml.unattend.Extensions.ExtractScript ); Invoke-Command -ScriptBlock $sb -ArgumentList $xml;"
```

![image](https://github.com/user-attachments/assets/48e9155b-1af4-4a16-8825-029654eb5725)

**Comment by hoang-himself** [comment]
>You probably should add the `-NoExit` switch to keep the PowerShell window open so you can read any error messages

Great tip, thanks!

I found a question mark at the beginning of my xml that was not visible in vscode. Saving the file without BOM encoding solves it.
