### ISSUE TITLE
Delete Operating System Request

### ISSUE THREAD

**Issue by Victory61** [cschneegans/unattend-generator#105]
Good morning.
Using ISO 23H2 is it possible to delete the operating system request, having already selected it in the autounattend generator?
Thank you

![Immagine 2024-11-03 175517](https://github.com/user-attachments/assets/4f6be25e-a0f0-45fd-92ec-ee5b73c688ae)
![Immagine 2024-11-03 180311](https://github.com/user-attachments/assets/c7389ce0-9559-40a0-bd7c-ad59b51e5881)

**Comment by cschneegans** [comment]
That dialog does not appear under normal circumstances.

Since the _Date modified_ column shows a date of today, am I correct to assume that you use a custom image?

**Comment by Victory61** [comment]
Yes, with NTlite

**Comment by cschneegans** [comment]
autounattend.xml files generated by my service work best with the original .iso images downloaded by Microsoft. With these images, Windows Setup will automatically select the edition associated with the given product key, and the dialog shown above does not appear. If images modified by NTLite behave differently, I would assume that NTLite is to blame.

You can try to add an [InstallFrom](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-imageinstall-osimage-installfrom) element to your autounattend.xml file to specify _Windows 11 Pro_ image explicitly.
