### ISSUE TITLE
[FutureIssues] 24H2 based LTSC Issues

### ISSUE THREAD

**Issue by Hammerfest** [cschneegans/unattend-generator#11]
This may be LTSC specific, I have yet to try it on full blown 24H2 as its not out yet, while LTSC is partially out.

Bloatware did not get removed and Recovery partition remains despite all being checked and using the remove option.

Haven't had a moment to check the rest, just redid the image twice to make sure.

Let me know if you need anything from me.

**Comment by cschneegans** [comment]
Using the evaluation .iso image [26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso](https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso), I can reproduce your findings. Thank you for bringing this to my attention!

• When the `RecoveryMode=None` query string parameter is set, no recovery partition is created during the WindowsPE phase of Windows Setup. This is the expected behavior. However, it seems that Windows Setup automatically creates the recovery partition during a later stage, at the end of the disk. I don't know yet if this can be avoided. Since `RecoveryMode=None` also deletes the `C:\Windows\System32\Recovery\Winre.wim` file, Windows Setup cannot successfully install Windows RE, and the recovery partition remains empty.

• The bloatware removal logs (`C:\Windows\Temp\remove-packages.log`, `C:\Windows\Temp\remove-caps.log`, `C:\Windows\Temp\remove-features.log`) are suspiciously empty, but I think this is due to the fact that almost all of these components are missing from this image in the first place. Also note that `26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso` is about 650 MiB smaller than e.g. `Windows11_InsiderPreview_Client_x64_en-us_26080.iso`.

**Comment by Hammerfest** [comment]
No worries, the eval should be the same as the OEM release with the exception of not being convertible to full release.
I get my copy from work but you should be able to find the full version if you think the differences make a difference, its not like its hidden 🗡️ .

As for the bloatware, yes, most of it is gone, but paint, notepad, etc etc are still there so there is bloat to remove its just not doing it.

**Comment by cschneegans** [comment]
What is the output of

```
Set-StrictMode -Off;
$(
    Get-AppxPackage -AllUsers;
    Get-AppxProvisionedPackage -Online;
    Get-WindowsOptionalFeature -Online;
    Get-WindowsCapability -Online;
) | Where-Object -FilterScript {
    -join( $_.Name, $_.DisplayName, $_.PackageName, $_.FeatureName ) -match 'notepad|paint'
};
```
in an elevated PowerShell window? Note that there is a classic and modern variant of Notepad, and also there is Paint and Paint 3D.

I have just committed https://github.com/cschneegans/unattend-generator/commit/d9eccd9ebb65dce57bb202d3407590cfb46035e0, which provides better logging for bloatware removal. Ideally you would repeat the installation with a refreshed autounattend.xml. In any case, please send me the files `C:\Windows\Temp\remove*.log` and the autounattend.xml file used (there's a copy in `C:\Windows\Panther\unattend.xml`).

**Comment by Hammerfest** [comment]
Sorry for the delay.
As ive not deployed and just in test/image creation phase I have gone ahead and done a totally fresh install.
Find attached the autounattend I re-created today, sadly, there is no .log in the C\Win\Temp directory.
[autounattend.zip](https://github.com/user-attachments/files/15942383/autounattend.zip)

Here is the output you request as well:
![image](https://github.com/cschneegans/unattend-generator/assets/396831/117aacc9-aaf0-415d-b947-60e826f70103)

**Comment by cschneegans** [comment]
Using your `autounattend.xml` file (with one modification, see below) and the `26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso` image, Windows Setup removed both Notepad and Paint:

```
Name  : Microsoft.Windows.MSPaint~~~~0.0.1.0
State : NotPresent

Name  : Microsoft.Windows.Notepad~~~~0.0.1.0
State : NotPresent
```

Indeed, `C:\Windows\System32\notepad.exe` did no longer exist.

Windows Setup asked me for a _work or school account_, which I don't have. Instead, I let Windows Setup create a local user account using the `UserAccountMode=Unattended` query string value.

To be honest, I have no idea why this does not work for you, so I would really need to see the logfiles. When checking the `C:\Windows\Temp` folder, avoid using Windows Explorer. Instead, open an elevated PowerShell session and type these commands:

```
Get-Item -Path 'C:\Windows\Temp\remove*.ps1';
Get-Content -Path 'C:\Windows\Temp\remove*.log';
```

**Comment by Hammerfest** [comment]
Interesting, are you by chance letting the system connect to the internet?
I dont have the VM connected to the internet at all, and it doesnt prompt me for a work or school account at all, goes straight to local, its also using the bypassnro for your autounattend setup so it seems like that may be broken as well if you had to change useraccountmode.

**Comment by cschneegans** [comment]
Nice, disabling the network adapter in VMware let me use a local account without any modifications to your `autounattend.xml`. Still, bloatware removal works as before. In particular, `notepad.exe` is removed.

**Comment by Hammerfest** [comment]
Actually, I think I may have found another bug or limitation, it doesn't seem to wipe the drive prior to the partitioning commands
Meaning if you dont do it on a fresh disk the set from prior remains

EX: From a totally fresh disk, setup actually only prompts me for the key which is as the autounattend was designed, HOWEVER, when i try to do it over, I noticed my EFI partition size which I had changed in this new autounattend, did not change (default was 300, I set to 512), SO, I went back in, did a DPC during setup while asking for the key, and after that it prompted me for which disk to install it as if the autounattend was being read from the internal disk instead of the install disk

A simple restart fixed it, but the point here, is what your seeing is sadly a byproduct of this, you removed it before, and thinking it would clear the disk with the autounattend, it actually did not so your left with the remnants

**Comment by cschneegans** [comment]
Generating an `autounattend.xml` file with query string parameter `PartitionMode=Unattended` will always emit a diskpart script that contains a `CLEAN` command. This is also the case with the `autounattend.xml` file you posted earlier:

```
<RunSynchronousCommand wcm:action="add">
    <Order>1</Order>
    <Path>cmd.exe /c "&gt;&gt;"X:\diskpart.txt" echo SELECT DISK=0"</Path>
</RunSynchronousCommand>
<RunSynchronousCommand wcm:action="add">
    <Order>2</Order>
    <Path>cmd.exe /c "&gt;&gt;"X:\diskpart.txt" echo CLEAN"</Path>
</RunSynchronousCommand>
```
During the PE stage of Windows Setup, you can even inspect the `X:\diskpart.log` logfile to verify the disk has been wiped:

![image](https://github.com/cschneegans/unattend-generator/assets/30263434/8946f6f0-c69d-4701-afb6-1e5919ced261)

**Comment by Hammerfest** [comment]
I hear ya, and I see ya, but again, I used a prior installation, added the new script with the 512MB EFI, and after the script was done it was still the 300MB EFI I started with.

**Comment by Hammerfest** [comment]
Not yet closed as its still not removing apps, but I havent had time to poke.

It looks like Msft is doing something for the evaluation copy vs iot, will circle back this weekend, been super busy.

**Comment by Hammerfest** [comment]
Redownloading ISO's from Microsoft (if your interested in testing non evaluation, microsofts download links can be found here on github, they are the same I use from my account) for testing.

**Comment by Hammerfest** [comment]
OK!, finished my retesting.
Totally fresh VM's, as prior no internet access at all, fresh downloads, hash confirmed.

I have confirmed my prior findings and yours.
When it comes to the EVALUATION iso, it works
26100.1.240331-1435.ge_release_CLIENT_IOT_LTSC_EVAL_x64FRE_en-us.iso
When it comes to the ACTUAL OEM iso it does NOT work (no matter if LTSC or IoT LTSC is chosen as edition)
26100.1.240331-1435.ge_release_CLIENT_ENTERPRISES_OEM_x64FRE_en-us


So at the very least it will not work for LTSC 2024
I confirmed logs exist when using EVAL iso but not OEM
Somethings gotta be blocking them, either way, just a note, at the very least, application removal wont work with LTSC 2024.

**Comment by cschneegans** [comment]
I have now acquired the file `26100.1.240331-1435.ge_release_CLIENT_ENTERPRISES_OEM_x64FRE_en-us.iso` and installed each of the editions

- Windows 11 Enterprise LTSC
- Windows 11 IoT Enterprise LTSC
- Windows 11 IoT Enterprise Subscription LTSC

in a VMware machine (without a product key) and still cannot reproduce any issues. In particular, all relevant logfiles exist and have reasonable contents:

```
PS C:\> Get-ChildItem -LiteralPath C:\Windows\Temp\, C:\Windows\Setup\Scripts\ -filter *.log

    Directory: C:\Windows\Temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2024-07-22     07:01          17147 dd_vcredist_amd64_20240721220155.log
-a----        2024-07-22     07:01         129162 dd_vcredist_amd64_20240721220155_000_vcRuntimeMinimum_x64.log
-a----        2024-07-22     07:01         135696 dd_vcredist_amd64_20240721220155_001_vcRuntimeAdditional_x64.log
-a----        2024-07-22     07:01          16308 dd_vcredist_x86_20240721220153.log
-a----        2024-07-22     07:01         128398 dd_vcredist_x86_20240721220153_000_vcRuntimeMinimum_x86.log
-a----        2024-07-22     07:01         140746 dd_vcredist_x86_20240721220153_001_vcRuntimeAdditional_x86.log
-a----        2024-07-22     07:00          91902 msedge_installer.log
-a----        2024-07-22     07:01           4278 remove-caps.log
-a----        2024-07-22     07:01            150 remove-features.log
-a----        2024-07-22     07:01           6650 remove-packages.log
-a----        2024-07-22     07:01            106 VBoxGuestAdditions.log
-a----        2024-07-22     07:02            148 VirtIoGuestTools.log
-a----        2024-07-22     07:02         213024 vminst.log
-a----        2024-07-22     07:02        2105106 vmmsi.log_20240721_220218.log
-a----        2024-07-21     22:02           7040 vmware-vmsvc-SYSTEM.log
-a----        2024-07-21     22:19            475 vmware-vmtoolsd-Administrator.log
-a----        2024-07-21     22:02           1425 vmware-vmtoolsd-SYSTEM.log
-a----        2024-07-21     22:19              0 vmware-vmusr-Administrator.log
-a----        2024-07-21     22:02           3258 vmware-vmusr-SYSTEM.log
-a----        2024-07-22     07:01              0 VMwareTools.log
-a----        2024-07-22     07:02          41096 wdac.log
-a----        2024-07-22     07:01            118 wifi.log

    Directory: C:\Windows\Setup\Scripts

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2024-07-22     07:02            111 unattend-01.log
-a----        2024-07-22     07:02            502 unattend-02.log
-a----        2024-07-22     07:02            889 unattend-03.log
-a----        2024-07-22     07:02              0 unattend-04.log
-a----        2024-07-22     07:02            582 unattend-05.log
-a----        2024-07-22     07:02            124 unattend-06.log
-a----        2024-07-22     07:02             40 unattend-07.log
-a----        2024-07-22     07:02             40 unattend-08.log
-a----        2024-07-22     07:02           2795 unattend-09.log
-a----        2024-07-22     07:02             40 unattend-0e.log

PS C:\> Get-ChildItem -LiteralPath C:\Windows\Temp -Filter remove*.log | Get-Content | ConvertFrom-Json | Format-Table -AutoSize -Property Selector, Message

Selector                               Message
--------                               -------
Browser.InternetExplorer               Capability removed.
MathRecognizer                         Capability removed.
OpenSSH.Client                         Capability removed.
Microsoft.Windows.MSPaint              Capability removed.
Microsoft.Windows.PowerShell.ISE       Capability removed.
App.Support.QuickAssist                Capability not installed.
Microsoft.Windows.SnippingTool         Capability removed.
App.StepsRecorder                      Capability removed.
Media.WindowsMediaPlayer               Capability removed.
Microsoft.Windows.WordPad              Capability not installed.
Microsoft-SnippingTool                 Feature not installed.
Microsoft.Microsoft3DViewer            Package not installed.
Microsoft.BingSearch                   Package not installed.
Microsoft.WindowsCalculator            Package not installed.
Microsoft.WindowsCamera                Package not installed.
Clipchamp.Clipchamp                    Package not installed.
Microsoft.WindowsAlarms                Package not installed.
Microsoft.549981C3F5F10                Package not installed.
Microsoft.Windows.DevHome              Package not installed.
MicrosoftCorporationII.MicrosoftFamily Package not installed.
Microsoft.WindowsFeedbackHub           Package not installed.
Microsoft.GetHelp                      Package not installed.
Microsoft.Getstarted                   Package not installed.
microsoft.windowscommunicationsapps    Package not installed.
Microsoft.WindowsMaps                  Package not installed.
Microsoft.BingNews                     Package not installed.
Microsoft.WindowsNotepad               Package not installed.
Microsoft.MicrosoftOfficeHub           Package not installed.
Microsoft.Office.OneNote               Package not installed.
Microsoft.OutlookForWindows            Package not installed.
Microsoft.Paint                        Package not installed.
Microsoft.MSPaint                      Package not installed.
Microsoft.People                       Package not installed.
Microsoft.Windows.Photos               Package not installed.
Microsoft.PowerAutomateDesktop         Package not installed.
MicrosoftCorporationII.QuickAssist     Package not installed.
Microsoft.SkypeApp                     Package not installed.
Microsoft.ScreenSketch                 Package not installed.
Microsoft.MicrosoftSolitaireCollection Package not installed.
Microsoft.MicrosoftStickyNotes         Package not installed.
MSTeams                                Package not installed.
Microsoft.Todos                        Package not installed.
Microsoft.WindowsSoundRecorder         Package not installed.
Microsoft.BingWeather                  Package not installed.
Microsoft.WindowsTerminal              Package not installed.
Microsoft.Xbox.TCUI                    Package not installed.
Microsoft.XboxApp                      Package not installed.
Microsoft.XboxGameOverlay              Package not installed.
Microsoft.XboxGamingOverlay            Package not installed.
Microsoft.XboxIdentityProvider         Package not installed.
Microsoft.XboxSpeechToTextOverlay      Package not installed.
Microsoft.GamingApp                    Package not installed.
Microsoft.YourPhone                    Package not installed.
Microsoft.ZuneMusic                    Package not installed.
Microsoft.ZuneVideo                    Package not installed.
```

Note that the above commands must be run in an elevated PowerShell session.

**Comment by Hammerfest** [comment]
Myself and now 4 others have confirmed, not sure what your doing wrong.

**Comment by Hammerfest** [comment]
I am leaving this ticket as closed, but its still happening sometimes

I know not the reason, happens sometimes with both direct install and windows to go install

**Comment by Hammerfest** [comment]
@cschneegans 
It seems like the Windows Recovery partition being created with 24H2 and beyond is not going to be resolved, do you have any idea's to automate its deletion with the script?

**Comment by cschneegans** [comment]
> It seems like the Windows Recovery partition being created with 24H2 and beyond is not going to be resolved, do you have any idea's to automate its deletion with the script?

Assuming a GPT disk created with the default partitions, this script added to the **FirstLogon scripts** section will delete the recovery partition (4) and resize the Windows partition (3):

```
$path = 'C:\Windows\Setup\Scripts\delete-recovery-partition.txt';
@(
	'SELECT DISK 0';
	'SELECT PARTITION 4';
	'DELETE PARTITION OVERRIDE';
	'SELECT PARTITION 3';
	'EXTEND'
) | Out-File -FilePath $path -Encoding 'ascii';
diskpart.exe /s $path;
```

**Comment by Hammerfest** [comment]
> > It seems like the Windows Recovery partition being created with 24H2 and beyond is not going to be resolved, do you have any idea's to automate its deletion with the script?
> 
> Assuming a GPT disk created with the default partitions, this script added to the **FirstLogon scripts** section will delete the recovery partition (4) and resize the Windows partition (3):
> 
> ```
> $path = 'C:\Windows\Setup\Scripts\delete-recovery-partition.txt';
> @(
> 	'SELECT DISK 0';
> 	'SELECT PARTITION 4';
> 	'DELETE PARTITION OVERRIDE';
> 	'SELECT PARTITION 3';
> 	'EXTEND'
> ) | Out-File -FilePath $path -Encoding 'ascii';
> diskpart.exe /s $path;
> ```

Appreciate it, will give it ago.

Also discovered they seem to have broken make edge uninstallable again somehow, le sigh~
EDIT: log for the script is a 0 byte file, and manually running it gives an ourfile error:
Out-File : Access to the path 'C:\Windows\System32\IntegratedServicesRegionPolicySet.json' is denied.
At C:\Windows\Setup\Scripts\MakeEdgeUninstallable.ps1:14 char:34
+         $o | ConvertTo-Json -Depth 9 | Out-File @params;
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
