### ISSUE TITLE
how do i stop scripts running

### ISSUE THREAD

**Issue by slaygirlz** [cschneegans/unattend-generator#110]
![image](https://github.com/user-attachments/assets/a341c44b-9c7a-44fe-b329-7bd04a51d1bf)
i have selected this as my automation i want the script to stop so when a new user gets created desktop flashes and removes

**Comment by cschneegans** [comment]
I am quite sure what you mean. If you had selected the _Delete preset icons … from the taskbar_ setting when you created the autounattend.xml file and now want to disable this setting for all users created from now on, you can perform these steps:

1. Open the file `C:\windows\Setup\Scripts\UserOnce.ps1` in a text editor with elevated permissions.
2. Locate the `Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\TaskbarIcons.ps1' -Raw | Invoke-Expression;` line.
3. Delete that line and save the file.

**Comment by slaygirlz** [comment]
thank you sorry about the confusion
