### ISSUE TITLE
[REQUEST] Disable Notifications

### ISSUE THREAD

**Issue by johnw41** [cschneegans/unattend-generator#111]
Hello.
How can disable some notifications
1. Personalisation-Start. all this notification
2. Privacy & Security- General. all this notification
3. Privacy & Security- Notifications
Thanks

**Comment by cschneegans** [comment]
I understand that you would like to disable these settings:

![image](https://github.com/user-attachments/assets/8c2e652b-f0f3-4ba2-9289-de9a80569ebd)

![image](https://github.com/user-attachments/assets/51f54b9c-98cd-4a7c-80bd-6b1a48b62691)

But I am not quite sure where to find the third setting you are referring to.

**Comment by cschneegans** [comment]
Note to self:

_Personalization > Start > Show account-related notifications_ can be be disabled with this .reg file:

```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Start_AccountNotifications"=dword:00000000
```

_Privacy & security > General > Show me notifications in the Settings app_ can be disabled with this .reg file:

```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\SystemSettings\AccountNotifications]
"EnableAccountNotifications"=dword:00000000
```

**Comment by johnw41** [comment]
I just add them to my autounattend file.
Thank you very much. Great page, perfect generator

**Comment by johnw41** [comment]
![not1](https://github.com/user-attachments/assets/52974a3d-7617-4851-9c93-8d7f189b1fce)
![not2](https://github.com/user-attachments/assets/06ee14a5-9a70-4823-a6c0-4075ecad25b9)
 I search also for this settings to disable. Any idea?

**Comment by cschneegans** [comment]
Check these registry keys:

```
HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener
HKLM\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener
HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics
HKLM\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics
```

**Comment by johnw41** [comment]
Thanks for the help. its the second setting from photo 1 & second setting from photo 2.

I run a reg file for test. 
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics]
"Value"="Deny"  

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener]
"Value"="Deny"

in registry is still "allow". i change it to "Deny" and i export this settings from registy. 
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics]
"Value"="Deny"
"LastSetTime"=hex(b):94,43,a3,74,3a,43,db,01

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener]
"Value"="Deny"
"LastSetTime"=hex(b):d6,12,58,5e,3a,43,db,01

I delete the settings from registry and run the new reg file and now works.
I check it again in next test of windows.
Thanks
