### ISSUE TITLE
[REQUEST] Disable mouse acceleration

### ISSUE THREAD

**Issue by boginhyr** [cschneegans/unattend-generator#114]
Is it possible to add an option to disable mouse acceleration?

**Comment by cschneegans** [comment]
Where is this setting in the UI? Only possible match I can find is this checkbox of `C:\WINDOWS\system32\main.cpl`:

![image](https://github.com/user-attachments/assets/a77bf761-4cfb-4298-94a9-221568a0c11a)

**Comment by stimpy81** [comment]
This is a great tweak for gamers!

**Comment by cschneegans** [comment]
Added setting via https://github.com/cschneegans/unattend-generator/commit/2bbf8145d5ebbd58deec6d9cb2054d129c150a6d:

![image](https://github.com/user-attachments/assets/df13a3e5-ec10-4b3b-a5e7-40f116c94d6e)
