### ISSUE TITLE
Skip Press any key to boot from CD or DVD...

### ISSUE THREAD

**Issue by TechGuruMaster** [cschneegans/unattend-generator#115]
Hello,

Is it possible to include this in the autounattend.xml? That way Windows 11 can install without needing to press any keys at all? 

Thanks!

**Comment by cschneegans** [comment]
That not possible using the autounattend.xml file – you would have to modify the Windows bootloader files.

**Comment by TechGuruMaster** [comment]
Any software you recommend that can accomplish this?

Appreciate your time and help!

Sincerely,
Brandon Garcia

**Comment by cschneegans** [comment]
I did not mean to imply that such a software exists.
