### ISSUE TITLE
[REQUEST] Disable bing search

### ISSUE THREAD

**Issue by boginhyr** [cschneegans/unattend-generator#118]
I would like to ask if an option could be added to disable bing search in start? I attach an image to better explain and an article for how to disable it [article from how to geek](https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/)
![IMG_1282](https://github.com/user-attachments/assets/10b43eb3-f469-48d6-a9a5-d6cd0d0d1831)

**Comment by stimpy81** [comment]
Actually, anything that removes Bing in general across the OS and browser would be a magical thing!

**Comment by cschneegans** [comment]
Added option to disable Bing search via https://github.com/cschneegans/unattend-generator/commit/263a4b5ed175afd118cf62fe303a4f1278008d95:

![image](https://github.com/user-attachments/assets/67954138-5653-4ad4-87d9-b3c45e05b1cf)

Note that setting this registry value with a .reg file such as

```
[HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Explorer]
"DisableSearchBoxSuggestions"=dword:00000001
```

or an equivalent reg.exe call is **not** correct in the general case. [Günter Born correctly points out](https://borncity.com/win/2020/10/05/windows-10-disable-bing-in-the-search/) that a non-admin user has no write permissions on his own `[HKEY_CURRENT_USER\Software\Policies]` key. Therefore, the commit mentioned above had to insert its call not in `UserOnce.ps1`, but in `DefaultUser.ps1`.
