### ISSUE TITLE
Windows.old folder issue

### ISSUE THREAD

**Issue by 1900forever** [cschneegans/unattend-generator#12]
Somehow after new installation by using the xml file generated by the website, there is an empty Windows.old folder under C partition.
Also, I put a registry key entry under "Scripts to run whenever a user logs on for the first time" section, but it seems not working for new (network) users' first login.

**Comment by cschneegans** [comment]
When performing an unattended installation e.g. of Windows 11 24H2 from the `Windows11_InsiderPreview_Client_x64_en-us_26100.iso` image, I also see an empty `C:\Windows.old` folder. However, this folder also appears when no `autounattend.xml` file is used at all, so this seems to be an oversight on Microsoft's part.

All custom scripts are stored in `C:\Windows\Setup\Scripts`. If you entered only one .reg file, its path will be `C:\Windows\Setup\Scripts\unattend-01.reg`. To analyze the problem, please login with the new account, then open the command prompt, type `reg.exe import "C:\Windows\Setup\Scripts\unattend-01.reg"` and verify the output is _The operation completed successfully._

**Comment by 1900forever** [comment]
Just verified the issue is not from the configuration file, it was restricted by GP: ERROR: Registry editing has been disabled by your administrator.
