### ISSUE TITLE
first login scripts

### ISSUE THREAD

**Issue by lapo70** [cschneegans/unattend-generator#121]
either cmd or powershell script can copy file to first login users desktop. Can You help?
Copy-Item "d:\computerregistration.exe" -Destination "$env:USERPROFILE\Desktop"
copy-Item "d:\computerregistration.cmd" -Destination "$env:USERPROFILE\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by cschneegans** [comment]
Your second `Copy-Item` call is missing a closing quote character. When you inspect `C:\Windows\Setup\Scripts\FirstLogon.log`, you should see a error message similar to this one:

```
Invoke-Expression: The string is missing the terminator: ".
```

**Comment by lapo70** [comment]
Thanks, I just forget to put it in my request. It is there in script. firstlogon.log is empty. Firstlogon.ps1 looks like  this:
$scripts = @(
	{
		Set-ItemProperty -LiteralPath 'Registry::HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoLogonCount' -Type 'DWord' -Force -Value 0;
	};
	{
		cmd.exe /c "rmdir C:\Windows.old";
	};
);

& {
	[float] $complete = 0;
	[float] $increment = 100 / $scripts.Count;
	foreach( $script in $scripts ) {
		Write-Progress -Activity 'Running scripts to finalize your Windows installation. Do not close this window.' -PercentComplete $complete;
		& $script;
		$complete += $increment;
	}
} *>&1 >> "C:\Windows\Setup\Scripts\FirstLogon.log";

**Comment by cschneegans** [comment]
> Thanks, I just forget to put it in my request. It is there in script.

Well, I had checked my webserver logs (searched for »d:\computerregistration.cmd«), and the closing quote character was missing there as well.

The FirstLogon.ps1 file you posted looks incomplete – there should be a call to a custom .ps1 file in there. [This link](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=sv-SE&Locale=sv-SE&Keyboard=0000041d&GeoLocation=221&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&ComputerNameMode=Script&ComputerNameScript=%24SerialNumber+%3D+%28Get-WmiObject+-class+win32_bios%29.SerialNumber%0D%0Aif+%28%24SerialNumber.length+-le+10%29%7B%0D%0A%24SerialNumber%3D%24SerialNumber%0D%0A%7Delse+%7B%0D%0A%24SerialNumber+%3D+%24SerialNumber.Substring%28%24SerialNumber.length+-+11%29%0D%0A%7D++%0D%0A%24computer+%3D+%22UUC-%24SerialNumber%22++%0D%0Areturn+%24computer+&CompactOsMode=Never&TimeZoneMode=Explicit&TimeZone=W.+Europe+Standard+Time&PartitionMode=Unattended&PartitionLayout=GPT&EspSize=300&RecoveryMode=None&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=&AccountGroup0=Administrators&AccountName1=User&AccountPassword1=&AccountGroup1=Users&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=None&TaskbarSearch=Box&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&DeleteTaskbarIcons=true&LaunchToThisPC=true&EnableLongPaths=true&EnableRemoteDesktop=true&AllowPowerShellScripts=true&DisableAppSuggestions=true&HideEdgeFre=true&WifiMode=Skip&ExpressSettings=DisableAll&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&StartTilesMode=Default&StartPinsMode=Default&FirstLogonScript0=Copy-Item+%22d%3A%5Ccomputerregistration.exe%22+-Destination+%22%24env%3AUSERPROFILE%5CDesktop%22%3B%0D%0ACopy-Item+%22d%3A%5Ccomputerregistration.cmd%22+-Destination+%22%24env%3AUSERPROFILE%5CAppData%5CRoaming%5CMicrosoft%5CWindows%5CStart+Menu%5CPrograms%5CStartup%22%3B&FirstLogonScriptType0=Ps1&WdacMode=Skip) will configure the form and add the missing quote character to your script. The resulting FirstLogon.ps1 file will look like this:

```
$scripts = @(
  {
    Set-ItemProperty -LiteralPath 'Registry::HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoLogonCount' -Type 'DWord' -Force -Value 0;
  };
  {
    cmd.exe /c "rmdir C:\Windows.old";
  };
  {
    Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\unattend-01.ps1' -Raw | Invoke-Expression;
  };
);

& {
  [float] $complete = 0;
  [float] $increment = 100 / $scripts.Count;
  foreach( $script in $scripts ) {
    Write-Progress -Activity 'Running scripts to finalize your Windows installation. Do not close this window.' -PercentComplete $complete;
    & $script;
    $complete += $increment;
  }
} *>&1 >> "C:\Windows\Setup\Scripts\FirstLogon.log";
```

Note the call to `C:\Windows\Setup\Scripts\unattend-01.ps1`, which in turn will contain your two `Copy-Item` commands.

**Comment by lapo70** [comment]
Thanks. Sorry about taking too much of your time but "this link" does not change anything. I just don't know where to put unattend-01.ps1 on the form and on installation media (USB) and how command to call it should look like. In form it looks like below. I hope You have time to explain.
Run
Copy-Item "d:\computerregistration.exe" -Destination "$env:USERPROFILE\Desktop";
Copy-Item "d:\computerregistration.cmd" -Destination "$env:USERPROFILE\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup";
as a 
.ps1
 file.
Run
setx.exe DIRCMD "/A /O:GN /C /N"
as a 
.cmd
 file.

**Comment by cschneegans** [comment]
The [link I posted](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=sv-SE&Locale=sv-SE&Keyboard=0000041d&GeoLocation=221&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&ComputerNameMode=Script&ComputerNameScript=%24SerialNumber+%3D+%28Get-WmiObject+-class+win32_bios%29.SerialNumber%0D%0Aif+%28%24SerialNumber.length+-le+10%29%7B%0D%0A%24SerialNumber%3D%24SerialNumber%0D%0A%7Delse+%7B%0D%0A%24SerialNumber+%3D+%24SerialNumber.Substring%28%24SerialNumber.length+-+11%29%0D%0A%7D++%0D%0A%24computer+%3D+%22UUC-%24SerialNumber%22++%0D%0Areturn+%24computer+&CompactOsMode=Never&TimeZoneMode=Explicit&TimeZone=W.+Europe+Standard+Time&PartitionMode=Unattended&PartitionLayout=GPT&EspSize=300&RecoveryMode=None&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=&AccountGroup0=Administrators&AccountName1=User&AccountPassword1=&AccountGroup1=Users&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=None&TaskbarSearch=Box&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&DeleteTaskbarIcons=true&LaunchToThisPC=true&EnableLongPaths=true&EnableRemoteDesktop=true&AllowPowerShellScripts=true&DisableAppSuggestions=true&HideEdgeFre=true&WifiMode=Skip&ExpressSettings=DisableAll&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&StartTilesMode=Default&StartPinsMode=Default&FirstLogonScript0=Copy-Item+%22d%3A%5Ccomputerregistration.exe%22+-Destination+%22%24env%3AUSERPROFILE%5CDesktop%22%3B%0D%0ACopy-Item+%22d%3A%5Ccomputerregistration.cmd%22+-Destination+%22%24env%3AUSERPROFILE%5CAppData%5CRoaming%5CMicrosoft%5CWindows%5CStart+Menu%5CPrograms%5CStartup%22%3B&FirstLogonScriptType0=Ps1&WdacMode=Skip) earlier will configure the form as you did initially, but adds the missing quote character. Check the corresponding textarea control to confirm this:

![image](https://github.com/user-attachments/assets/4450a6c6-e1e5-4401-b7d5-03f2a28e16f5)

When you then click the _View .xml file_ or _Download .xml file_ button, you will get an .xml file that
- has your PowerShell code embedded in a `<File path="C:\Windows\Setup\Scripts\unattend-01.ps1" transformation="Text">…</File>` element,
- calls this script file using the `Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\unattend-01.ps1' -Raw | Invoke-Expression;` statement.

You do not have to create the `unattend-01.ps1` file yourself.

**Comment by lapo70** [comment]
Hello,
I'm feeling very stupid but "calls this script..." where to call it from and where to put my powershell code? There is no unattend-01.ps1 in that path "c:\windows....

Forgiv my confusion.


Kind regards, Pavle

________________________________

**Comment by lapo70** [comment]
Thanks. Sorry about taking too much of your time but "this link" does not change anything. I just don't know where to put unattend-01.ps1 and how command to call it should look like.

**Comment by cschneegans** [comment]
You don't have to save or call unattend-01.ps yourself – this is handled by the autounattend.xml file automatically.
