### ISSUE TITLE
When installing using `setup.exe /unattend:unattend.xml`, Defender was not disabled.

### ISSUE THREAD

**Issue by xlk9jjlv** [cschneegans/unattend-generator#122]
I mounted the ISO and executed the command `setup.exe /unattend:autounattend.xml` to install the system. The following GIF shows the operation process.
![GIF](https://github.com/user-attachments/assets/ea11dd29-3a63-4bde-aef2-a0158cbf3c1f)

This is the answer file I [Generate autounattend.xml files for Windows 10/11](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=zh-CN&Locale=zh-Hans-CN&Keyboard=0804%3A%7B81d4e9c9-1d3b-41bc-9e6c-4b40bf79e35e%7D%7Bfa550b04-5ad7-411f-a5ac-ca038ec515d7%7D&GeoLocation=45&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Random&CompactOsMode=Default&TimeZoneMode=Implicit&PartitionMode=Custom&DiskpartScript=REM&InstallToMode=Available&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=&AccountGroup0=Administrators&AccountName1=&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=HiddenSystem&TaskbarSearch=Hide&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&LeftTaskbar=true&DeleteTaskbarIcons=true&HideTaskViewButton=true&LaunchToThisPC=true&DisableDefender=true&DisableWindowsUpdate=true&DisableUac=true&DisableSac=true&DisableSmartScreen=true&DisableFastStartup=true&DisableSystemRestore=true&EnableLongPaths=true&HardenSystemDriveAcl=true&AllowPowerShellScripts=true&DisableLastAccess=true&PreventAutomaticReboot=true&DisableAppSuggestions=true&PreventDeviceEncryption=true&HideEdgeFre=true&WifiMode=Skip&ExpressSettings=DisableAll&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&Remove3DViewer=true&RemoveBingSearch=true&RemoveCamera=true&RemoveClipchamp=true&RemoveClock=true&RemoveCopilot=true&RemoveCortana=true&RemoveDevHome=true&RemoveFamily=true&RemoveFeedbackHub=true&RemoveGetHelp=true&RemoveHandwriting=true&RemoveInternetExplorer=true&RemoveMailCalendar=true&RemoveMaps=true&RemoveMathInputPanel=true&RemoveMediaFeatures=true&RemoveMixedReality=true&RemoveZuneVideo=true&RemoveNews=true&RemoveOffice365=true&RemoveOneDrive=true&RemoveOneNote=true&RemoveOneSync=true&RemoveOpenSSHClient=true&RemoveOutlook=true&RemovePaint=true&RemovePaint3D=true&RemovePeople=true&RemovePhotos=true&RemovePowerAutomate=true&RemovePowerShell2=true&RemovePowerShellISE=true&RemoveQuickAssist=true&RemoveRecall=true&RemoveRdpClient=true&RemoveSkype=true&RemoveSnippingTool=true&RemoveSolitaire=true&RemoveSpeech=true&RemoveStepsRecorder=true&RemoveStickyNotes=true&RemoveTeams=true&RemoveGetStarted=true&RemoveToDo=true&RemoveVoiceRecorder=true&RemoveWallet=true&RemoveWeather=true&RemoveFaxAndScan=true&RemoveWindowsHello=true&RemoveWindowsMediaPlayer=true&RemoveZuneMusic=true&RemoveWindowsTerminal=true&RemoveWordPad=true&RemoveXboxApps=true&RemoveYourPhone=true&StartTilesMode=Empty&StartPinsMode=Empty&WdacMode=Skip)

The following is the result of checking the status using a command.
```
PS C:\Users\Admin> Get-ChildItem -LiteralPath C:\Windows\Temp -Force -Filter remove*.log | Get-Content | ConvertFrom-Json


PS C:\Users\Admin> Get-Service -Name Sense, WdBoot, WdFilter, WdNisDrv, WdNisSvc, WinDefend | Format-Table -AutoSize -Property Name, Status, StartType

Name       Status StartType
----       ------ ---------
Sense     Stopped    Manual
WdBoot    Stopped      Boot
WdFilter  Running      Boot
WdNisDrv  Running    Manual
WdNisSvc  Running    Manual
WinDefend Running Automatic


PS C:\Users\Admin> Get-Process -Name MsMpEng

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    928      84   182788     191920      29.91   3552   0 MsMpEng
```

I downloaded the system from [NEXT, ITELLYOU](https://next.itellyou.cn/).
In the Windows 10 downloaded from Microsoft, using the command `setup.exe /unattend:unattend.xml`, Defender was also not disabled.

![GIF](https://github.com/user-attachments/assets/b7e55653-e52f-49af-977d-7c3c275b7e19)

Windows 10 (business edition), version 2004 (updated Sep 2020) (x64) - DVD (Chinese-Simplified)

Verification information:
> 文件：cn_windows_10_business_editions_version_2004_updated_sep_2020_x64_dvd_7134ba4b.iso
> 大小：4.95GB
> MD5：99D7C88AED369CFE8BA11F7B041BC044
> SHA1：BF0874FFE0FAE1C557E65F49B83B5E83BE7DBF24
> SHA256：E9872C5A571624E9FBB6B660B415FD214DD67364AE2A584ADBC4C1D037E565F7

Download method:
BT
> magnet:?xt=urn:btih:C74F64E50F4FACBA15D0870791E0CB09336D6057&dn=cn_windows_10_business_editions_version_2004_updated_sep_2020_x64_dvd_7134ba4b.iso&xl=5313628160

ED2K
> ed2k://|file|cn_windows_10_business_editions_version_2004_updated_sep_2020_x64_dvd_7134ba4b.iso|5313628160|7CF0E7C3324B4209663B8B971A5ACEF2|/

**Comment by cschneegans** [comment]
Windows Defender services are disabled [by a script](https://github.com/cschneegans/unattend-generator/blob/master/resource/DisableDefender.vbs) that runs during the _windowsPE_ phase of Windows Setup, i.e. when you boot from a DVD or thumb drive. This is necessary because in Windows 11 these services cannot easily be disabled once they are running.

I am not at all familiar with Windows Setup being launched from within Windows. To be honest, I am surprised that the autounattend.xml file is applied at all in this scenario. In any case, the scripts in the `<settings pass="windowsPE">…<settings>` section of the autounattend.xml file will not be processed.

**Comment by xlk9jjlv** [comment]
> Windows Defender services are disabled [by a script](https://github.com/cschneegans/unattend-generator/blob/master/resource/DisableDefender.vbs) that runs during the _windowsPE_ phase of Windows Setup, i.e. when you boot from a DVD or thumb drive. This is necessary because in Windows 11 these services cannot easily be disabled once they are running.
> 
> I am not at all familiar with Windows Setup being launched from within Windows. To be honest, I am surprised that the autounattend.xml file is applied at all in this scenario. In any case, the scripts in the section of the autounattend.xml file will not be processed.`<settings pass="windowsPE">…<settings>`

I didn't look closely; Defender is not disabled, but things like deleting the calculator were successful.
