### ISSUE TITLE
 Change Key Sequence. Grave Accent (`) 

### ISSUE THREAD

**Issue by sumonchai** [cschneegans/unattend-generator#124]
How to set the grave accent key (`) as input language switcher, how do you type the grave accent?

**Comment by cschneegans** [comment]
You choose your desired keyboard layout here:

![image](https://github.com/user-attachments/assets/ce6488c3-4189-4e41-99e5-c97ed079ca39)

If there is no keyboard layout that offers the desired behavior, I assume you need to install additional software like [PowerToys Keyboard Manager](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager).
