### ISSUE TITLE
Restore features broken my Edge Removal

### ISSUE THREAD

**Issue by rcmaehl** [cschneegans/unattend-generator#125]
If possible, implement @Aveyo's "[OpenWebSearch](https://github.com/AveYo/fox/blob/main/ChrEdgeFkOff.cmd)" which will restore some functionality that is broken when Edge is removed by redirecting that functionality to the default browser

**Comment by cschneegans** [comment]
If you want to use that script, run it as a custom script, probably in the _Scripts to run in the system context, before user accounts are created_ section.

I have no intention to include that script (which would easily double the size of a typical autounattend.xml file) in my code, sorry.
