### ISSUE TITLE
Plain text off?

### ISSUE THREAD

**Issue by 1900forever** [cschneegans/unattend-generator#13]
Can we set password plain text to off under Microsoft-Windows-Shell-Setup\UserAccounts section?
I need to enable the built-in Administrator account, and I have to copy and past the encrypted password from Windows System Image Manager every time I generated a new xml from the website.

**Comment by cschneegans** [comment]
Thanks for the suggestion. Added support for obscured account passwords with https://github.com/cschneegans/unattend-generator/commit/f763993b887e4edc4e1d9c493e3cde47521e4aca. On the [website](https://schneegans.de/windows/unattend-generator/), use the _Obscure all account passwords with Base64_ checkbox.

Note, however, that `<PlainText>false</PlainText>` does not mean encryption, but rather Base64 encoding. Hence, it will at best protect against someone looking over your shoulder.
