### ISSUE TITLE
[REQUEST] Workgroup

### ISSUE THREAD

**Issue by Rootzpower** [cschneegans/unattend-generator#130]
Hello

its possible to add option for choose name of workgroup?

Regards

**Comment by cschneegans** [comment]
You can always add a .ps1 script such as

```
Add-Computer -WorkGroupName 'Example';
```

in the _Scripts to run in the system context, before user accounts are created_ section.

A dedicated setting would just do the same thing. Unlike the computer name, the workgroup name does not seem to be easily accessible via the registry, or am I missing something?
