### ISSUE TITLE
[REQUEST] Remove edge during installation

### ISSUE THREAD

**Issue by greg34x** [cschneegans/unattend-generator#131]
Hello, is it also possible to add an option to directly uninstall edge instead of make it removable?
I wont use it if i ever need to download something i can use curl directly on cmd.

**Comment by cschneegans** [comment]
There are scripts that uninstall Edge (or at least claim to do so), but they are typically too complicated for my liking. If you want to use such scripts, you should probably put them in the _Scripts to run in the system context, before user accounts are created_ section.

I was very content with the [MakeEdgeUninstallable.ps1](https://github.com/cschneegans/unattend-generator/blob/master/resource/MakeEdgeUninstallable.ps1) script, but that approach [does no longer work in 24H2](https://github.com/cschneegans/unattend-generator/issues/81).

**Comment by greg34x** [comment]
@cschneegans what about removing the edge folders at `<settings pass="windowsPE">`
```
				<RunSynchronousCommand wcm:action="add">
					<Order>21</Order>
					<Path>cmd.exe /c "rmdir /s /q "C:\Program Files (x86)\Microsoft\Edge" &amp; rmdir /s /q "C:\Program Files (x86)\Microsoft\EdgeUpdate" &amp; timeout /t 25"</Path>
				</RunSynchronousCommand>
```I'm not sure whats wrong with the syntax but the installation is complaining about it

**Comment by cschneegans** [comment]
`C:\Program Files (x86)` does not yet exist when `RunSynchronousCommand` elements are processed. Windows Setup might even use a drive letter other than `C:` for the target volume during the windowsPE phase.

If you really want to meddle with files and folders on the target volume during the windowsPE phase, check how the [DisableDefender.vbs](https://github.com/cschneegans/unattend-generator/blob/master/resource/DisableDefender.vbs) script is implemented.

**Comment by greg34x** [comment]
I did some tests and i have been able to delete both folders during the `windowsPE` phase, trying to delete them on the moment the "specialize" scripts are executed i get a permission error.
I see how you are calling the defender scripts, i think its a problem on the syntax of the command, do you see something wrong on it?

**Comment by cschneegans** [comment]
The text value (i.e. after unescaping the XML markup) of the `<Path>` element must not exceed 256 characters in length. Your second command is 261 characters long.

**Comment by greg34x** [comment]
@cschneegans thanks i didn't know this.

Removing edge during the windowsPE phase worked, when the system started i don't have edge anywhere, but theres a catch i cant delete the folders while the files are being installed or it throw an error, i need to wait it finish everything until that point it restarts on 10seconds.

Do you have any idea how to stop it from rebooting while still using the unattended answer?

I have tried this:
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-automation-overview?view=windows-11#setupconfigini

but it is ignoring the option and auto rebooting.

**Comment by cschneegans** [comment]
> Do you have any idea how to stop it from auto rebooting while still using the unattended answer?

As far as I know, the new “ConX” setup.exe in 24H2 does not accept command line options at all. You would need to switch to legacy setup mode first. I do not know how that switch can be automated. See [my comment](https://github.com/cschneegans/unattend-generator/issues/116#issuecomment-2493555689) on how to do it manually.

**Comment by greg34x** [comment]
@cschneegans thanks ill try it.

```xml
				<RunSynchronousCommand wcm:action="add">
					<Order>21</Order>
					<Path>cmd.exe /c "start /MIN cscript.exe //E:removeedge E:\removeedge.vbs"</Path>
				</RunSynchronousCommand>
```
I have put it into the same root folder of the `setup.exe` but when the auto installation start it doesn't get called.
I test manually calling it opening shift+10 and it does work, just the auto start not.

**Comment by cschneegans** [comment]
When you already rebuild your .iso file, I think it would be far easier to remove the `C:\Program Files (x86)\Microsoft\Edge` folder in the .wim image.

**Comment by AzimsTech** [comment]
> There are scripts that uninstall Edge (or at least claim to do so), but they are typically too complicated for my liking. If you want to use such scripts, you should probably put them in the _Scripts to run in the system context, before user accounts are created_ section.
> 
> I was very content with the [MakeEdgeUninstallable.ps1](https://github.com/cschneegans/unattend-generator/blob/master/resource/MakeEdgeUninstallable.ps1) script, but that approach [does no longer work in 24H2](https://github.com/cschneegans/unattend-generator/issues/81).

The [MakeEdgeUninstallable.ps1](https://github.com/cschneegans/unattend-generator/blob/master/resource/MakeEdgeUninstallable.ps1) script still works in 24H2. 
You must install all Windows updates and run the script as TrustedInstaller. 
I recently tested it on a VM.

**Comment by cschneegans** [comment]
To my surprise, Edge on 24H2 can be uninstalled once again via _Settings > Apps_, no System or TrustedInstaller permissions required, only the modification to `IntegratedServicesRegionPolicySet.json` during Windows Setup. This is an excerpt from `C:\Windows\SystemTemp\msedge_installer.log` after I had Edge uninstalled:

```
[8904:8900:1211/162356.174:156843:VERBOSE1:install_util.cc(284)] Existing version found: 131.0.2903.86
[8904:8900:1211/162356.214:156875:VERBOSE1:edge_install_util.cc(216)] Parent process: C:\Windows\System32\sihost.exe
[8904:8900:1211/162356.214:156875:VERBOSE1:edge_install_util.cc(240)] Caller is not under windir environment variable.
[8904:8900:1211/162356.214:156875:VERBOSE1:edge_install_util.cc(256)] Uninstall allowed: Windows caller
[8904:8900:1211/162356.214:156875:VERBOSE1:shell_util.cc(4117)] Uninstall enabled by regional policy
[8904:8900:1211/162356.214:156875:VERBOSE1:edge_install_util.cc(280)] Uninstall allowed: Product is not sticky
```

I am not sure what triggered this change. Note that the very same process `C:\Windows\System32\sihost.exe` was excluded from uninstalling Edge when I commented on https://github.com/cschneegans/unattend-generator/issues/81 a few weeks back.

**Comment by AzimsTech** [comment]
@cschneegans Is the ISO from the MediaCreationTool (build 26100.2033) right?

**Comment by cschneegans** [comment]
> Is the ISO from the MediaCreationTool (build 26100.2033) right?

It's Win11_24H2_English_x64.iso, downloaded [directly](https://www.microsoft.com/en-us/software-download/windows11#SoftwareDownload_Edition), not through the Media Creation Tool.
