### ISSUE TITLE
[REQUEST] Auto-install software

### ISSUE THREAD

**Issue by johnw41** [cschneegans/unattend-generator#132]
Hello.
Is possible when Windows instalation finish to run some programs (i have fix it silent) from a folder of usb?

Thanks

**Comment by cschneegans** [comment]
That is precisely what the _Scripts to run when the first user logs on after Windows has been installed_ section is for. Note that the first user to log on is typically an administrator and those scripts will then run with elevated privileges by Windows Setup.

**Comment by johnw41** [comment]
For example, i have in folder D\Source\$OEM$\$$Pro\Setup\Scripts  the silent programs of 7ZIP.exe and Firefox.exe what script need to Scripts to run when the first user logs on after Windows has been installed section?

**Comment by cschneegans** [comment]
To run the 7-Zip installer **7z2409-x64.exe**, try this command as a .ps1 script:

```
Start-Process -FilePath 'D:\Source\$OEM$\$$Pro\Setup\Scripts\7z2409-x64.exe' -ArgumentList '/S /D="C:\Program Files\7-Zip"' -Wait;
```

To run the Firefox installer package **firefox.msi**, try this command as a .ps1 script:

```
Start-Process -FilePath 'D:\Source\$OEM$\$$Pro\Setup\Scripts\firefox.msi' -ArgumentList '/passive' -Wait;
```
