### ISSUE TITLE
Any planned changes now that MS removed some of the hardware restrictions for Win 11?

### ISSUE THREAD

**Issue by Pocokk** [cschneegans/unattend-generator#134]
Hey there!

I've seen a recent (today) news article about MS lessened certain restrictions regarding installing and running Windows 11 (more here https://support.microsoft.com/en-us/windows/installing-windows-11-on-devices-that-don-t-meet-minimum-system-requirements-0b2dc4a2-5933-4ad4-9c09-ef0a331518f1#:~:text=Die%20Installation%20von%20Windows%2011,vertraut%20sein,%20dass%20Kompatibilit%C3%A4tsprobleme%20auftreten.&xcust=2-1-2550265-1-0-0-0-0&sref=https://www.pcworld.com/article/2550265/microsoft-now-allowing-windows-11-on-older-incompatible-pcs.html)

Considering all these, do you plan to reconstruct some parts/elements of the unattend-generator?

Thank you!

**Comment by cschneegans** [comment]
Microsoft relaxing system requirements does not necessitate any changes for how autounattend.xml files are generated and/or used.

**Comment by Pocokk** [comment]
So it doesn't matter if I select certain options that would remove those restrictions or not?

**Comment by cschneegans** [comment]
If – and that's a big if – Microsoft chooses to relax certain hardware restrictions, the registry values generated by the _Bypass Windows 11 requirements_ option check would become redundant, but certainly not harmful.

**Comment by Pocokk** [comment]
Thank you, wasn't sure how it worked!
