### ISSUE TITLE
Windows Defender on 24H2

### ISSUE THREAD

**Issue by irfanjunaid** [cschneegans/unattend-generator#135]
Hello,
Thanks for this amazing tool 🙏 

I wanted to check if there is any criteria for disabling the Windows Defender on a Windows 11 24H2 release. I installed 24H2 from Bootable USB created by Media Creation tool. And, I checked in the option `Disable Windows Defender` for unattend.xml generator. Once Windows installed, after the login, I see the `MsMpEng.exe` is still running and Antivirus not disabled in the Windows Defender Security Center as well. I see a minimised command prompt window before the disk partitioning, do we need to wait for any process to completed. Please advise.

Thank you!

**Comment by cschneegans** [comment]
When the installation has finished, the expected result is that MsMpEng.exe is not running and several services are disabled and stopped:

```
PS C:\> Get-Process -Name MsMpEng;
Get-Process : Cannot find a process with the name "MsMpEng". Verify the process name and call the cmdlet again.

PS C:\> Get-Service -Name Sense, WdBoot, WdFilter, WdNisDrv, WdNisSvc, WinDefend | Format-Table -Property Name, StartType, Status;

Name      StartType  Status
----      ---------  ------
Sense      Disabled Stopped
WdBoot     Disabled Stopped
WdFilter   Disabled Stopped
WdNisDrv   Disabled Stopped
WdNisSvc   Disabled Stopped
WinDefend  Disabled Stopped
```

This should work on both Windows 10 and 11, including 24H2 – I have successfully installed 24H2 many times with Defender being disabled.

To identify any problems, bring the cscript.exe window to the front (Alt+Tab) and check its output, which should look similar to this:

![image](https://github.com/user-attachments/assets/985b2081-0518-4847-914c-8aed171974fa)

**Comment by irfanjunaid** [comment]
Thank you for the detailed steps. Sorry for the delay, was just debugging this issue with 23H2/24H2. May be this situation has to do something with my laptop specifically 🤔  My Thinkpad E16 is one of those machines where 24H2 is not officially available yet. May be that incompatibility is causing all these issues!? 🤷‍♂️ Infact, both `KB5046617 ` and `KB5048667 ` failed to install with some error from Windows update, even tried the `.msu` but no luck. May be I should wait until 24H2 is officially available for my hardware before attempting this again.

I checked the `cscript` window but the script ran too fast to notice and there were definitely some errors in 24H2 but everything is working flawlessly in 23H2. Does that script leave any log files with the command outputs? Not sure if my machine can handle so many Windows reinstalls(8) 😉 May be I should start debugging this in a VM...

**Comment by cschneegans** [comment]
The latest version of [DisableDefender.vbs](https://github.com/cschneegans/unattend-generator/blob/master/resource/DisableDefender.vbs) has a `WScript.Sleep 5000` call built-in, which should give you enough time to read the output. If your autounattend.xml file does not contain this `WScript.Sleep 5000` string, you should refresh it. To do so, [import](https://schneegans.de/windows/unattend-generator/) your existing file and download it again.

**Comment by irfanjunaid** [comment]
I was in hell with 24H2 last few days, but at least things are very bad with it for me. 12-2024 update is constantly failing on fresh install.

It seems it's already known: https://answers.microsoft.com/en-us/windows/forum/all/i-tried-to-install-the-version-24h2-kb5048667-but/bb656461-8967-46fc-8b45-150128ea3e6b

And BTW, following the above solution resulted in BSOD!!! 
I can reproduce the `0x80070302` error in a Hyper-V VM fresh 24H2 install with the XML.
And to debug this issue, When I installed 24H2 like a normal way, everything worked fine in the VM with updates. No errors faced.

I don't know which option in the tool/XML would cause the December update to fail(November update failed as well before but I thought it was some Windows issue/bug).

I give up with 24H2 for now 🏳️ 🏳️ 🏳️  Reinstalled 23H2 back...

**Comment by cschneegans** [comment]
The script output looks fine despite the error messages. These errors are expected and handled. The important thing is that the `reg.exe LOAD` call eventually succeeds. You should also see the output `Found and successfully modified SYSTEM registry hive file at 'C:\$Windows.~BT\NewOS\Windows\System32\config\SYSTEM'. This window will now close.` before the windows closes.

**Comment by irfanjunaid** [comment]
Got it, thank you. I will retry this when 24H2 is officially available for my laptop model. 23H2 is running like butter smooth without any issues.
