### ISSUE TITLE
[REQUEST] Add taskbar layout support into the existing start layout customisation

### ISSUE THREAD

**Issue by Jacosci** [cschneegans/unattend-generator#139]
As stated on the docs here: https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-the-taskbar
We can customise pinned items on taskbar using XML configurations too.

You can read further here along with some examples and how to include it to Start layout XML.
https://learn.microsoft.com/en-us/windows/configuration/taskbar/pinned-apps?tabs=intune&pivots=windows-10

**Comment by cschneegans** [comment]
Thanks, that's very interesting! Will look into it at once.

**Comment by cschneegans** [comment]
I have now added new settings (via https://github.com/cschneegans/unattend-generator/commit/f1baece44eb611eda869f0cfd57b569854adbc68) to choose between the default icons, no icons or custom icons in the taskbar:

![image](https://github.com/user-attachments/assets/ea5e5016-2a54-4909-ba15-9163438aba3a)

The _Delete preset icons … from the taskbar_ setting has been subsumed in this new setting. Existing URLs with query string parameter `DeleteTaskbar=true` will be rewritten to `TaskbarIconsMode=Empty`.

**Comment by Jacosci** [comment]
> I have now added new settings (via [f1baece](https://github.com/cschneegans/unattend-generator/commit/f1baece44eb611eda869f0cfd57b569854adbc68)) to choose between the default icons, no icons or custom icons in the taskbar:
> 
> ![image](https://private-user-images.githubusercontent.com/30263434/396344225-ea5e5016-2a54-4909-ba15-9163438aba3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY0MTcsIm5iZiI6MTczNDQyNjExNywicGF0aCI6Ii8zMDI2MzQzNC8zOTYzNDQyMjUtZWE1ZTUwMTYtMmE1NC00OTA5LWJhMTUtOTE2MzQzOGFiYTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNzg2ODUwYzRlYWFiMmJhMGI4NmVkOTBmMmVjYjJkOWZjYjkxNmQwMjlkZGFlOGRiZmNmMzEyNDM1M2QyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bkPpGZjECgbT7vp6hTPcI2k6XfiNM9ddlL57WTJCc6c)
> 
> The _Delete preset icons … from the taskbar_ setting has been subsumed in this new setting. Existing URLs with query string parameter `DeleteTaskbar=true` will be rewritten to `TaskbarIconsMode=Empty`.

Awesome! I'll do some testing soon and will report back if there's any issue.

**Comment by Jacosci** [comment]
I have tested this on Windows 10 Home and Enterprise and Windows 11 Home and it worked as intended. So it technically should work on any other Windows 10/11 editions.

There's a small caveat though. The start menu would get locked down as a result and that's by design. But if you don't want that, there's a workaround on Windows 10 if you apply partial start menu customisation by declaring this `<DefaultLayoutOverride LayoutCustomizationRestrictionType="OnlySpecifiedGroups">` on the start layout XML.

I haven't found a workaround on Windows 11. One thing I found is that both Start and taskbar layout customisations are retained if I manually change this registry key `HKLM\Software\Policies\Microsoft\Windows\Explorer\LockedStartLayout` value to 0. You can only do this after you logged on. If you modify the registry value before that then the customisations wouldn't be applied.

**Comment by Jacosci** [comment]
I think the referenced commits pretty much fixed this. So I'm going to close this issue.
