### ISSUE TITLE
RegisteredOwner and RegisteredOrganization

### ISSUE THREAD

**Issue by 1900forever** [cschneegans/unattend-generator#14]
Can we have more OEM options is the configuration file please? 😄

**Comment by cschneegans** [comment]
The functionality of [RegisteredOwner](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-registeredowner) and [RegisteredOrganization](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-registeredorganization) can easily be achieved by adding a .reg file in the **Scripts to run in the system context** section:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion]
"RegisteredOrganization"="Foo"
"RegisteredOwner"="Bar"
```
