### ISSUE TITLE
Prevent device encryption

### ISSUE THREAD

**Issue by wincmd64** [cschneegans/unattend-generator#140]
Thx for the generator, but over time the site became very complex and large.
**I only need ONE function: Prevent device encryption**.
Can you provide an example xml file that contains only this?

Thx.

**Comment by cschneegans** [comment]
[This link](https://schneegans.de/windows/unattend-generator/?LanguageMode=Interactive&ProcessorArchitecture=amd64&ComputerNameMode=Random&CompactOsMode=Default&TimeZoneMode=Implicit&PartitionMode=Interactive&WindowsEditionMode=Interactive&UserAccountMode=Interactive&PasswordExpirationMode=Default&LockoutMode=Default&HideFiles=Hidden&TaskbarSearch=Box&TaskbarIconsMode=Default&StartTilesMode=Default&StartPinsMode=Default&PreventDeviceEncryption=true&WifiMode=Interactive&ExpressSettings=Interactive&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&WdacMode=Skip) will configure the form to produce a minimal autounattend.xml file to prevent device encryption – just click the _View…_ or _Download…_ buttons at the bottom of that page. (The autounattend.xml file will also contain a script that deletes the `C:\Windows.old` folder after installation if it is empty, as that behavior is not configurable.)

**Comment by wincmd64** [comment]
No, that doesn't suit me. 107 lines and a powershell script 🤨

**ONE function**: Prevent device encryption. And that's all.

**Comment by cschneegans** [comment]
You are making a somewhat valid point, and I have taken the opportunity to add a button to configure the form such that a minimal file will be generated:

![image](https://github.com/user-attachments/assets/9290a61b-36fa-49f2-8706-c9de38833aea)

You probably won't like the end result, though, as the reg.exe call to set the _PreventDeviceEncryption_ registry value is still embedded in a PowerShell script. The generated autounattend.xml files heavily rely on PowerShell for almost all actions, and I have no intention to change this.

**Comment by wincmd64** [comment]
About a year ago, the site was still somehow usable. It was useful and compact.

Now it has become a monster. My finger hurts scrolling through all the options. If the values ​​NOT by default were highlighted, it would be fine, but now you still have to read carefully what is by default and what is not.

I asked for ONE simple function. In response, I received even more complications, some strange presets.

The horror... the horror... (c)

**Comment by stimpy81** [comment]
> About a year ago, the site was still somehow usable. It was useful and compact.
> 
> Now it has become a monster. My finger hurts scrolling through all the options. If the values ​​NOT by default were highlighted, it would be fine, but now you still have to read carefully what is by default and what is not.
> 
> I asked for ONE simple function. In response, I received even more complications, some strange presets.
> 
> The horror... the horror... (c)

Theres always one...  Good thing the rest of us find this service indispensable.
