### ISSUE TITLE
HOW TO USE  Use a distribution share / configuration set?

### ISSUE THREAD

**Issue by mashkvultr** [cschneegans/unattend-generator#145]
HOW TO USE  Use a distribution share / configuration set?    
How to use it in conjunction with autoresponders  （unattend.xml）

**Comment by cschneegans** [comment]
Assuming you are preparing an USB thumb drive to launch Windows Setup from, its root folder would look like this:

```
boot\
efi\
sources\
support\
$OEM$\
autorun.inf
bootmgr
bootmgr.efi
setup.exe
autounattend.xml
```

Place your content in the `$OEM$` folder according to [Microsoft's documentation](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/wsim/distribution-shares-and-configuration-sets-overview).
