### ISSUE TITLE
Enabling VirtIO installation is broken

### ISSUE THREAD

**Issue by lmb** [cschneegans/unattend-generator#18]
The generator currently outputs the following XML when [enabling virtio installation](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&UserLocale=en-US&KeyboardLayout=0409%3A00000409&GeoLocation=244&ProcessorArchitecture=amd64&ComputerNameMode=Random&TimeZoneMode=Implicit&PartitionMode=Unattended&PartitionLayout=GPT&EspSize=300&RecoveryMode=Folder&WindowsEditionMode=Unattended&WindowsEdition=pro_n&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=password&AccountGroup0=Administrators&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Disabled&DisableSystemRestore=true&AllowPowerShellScripts=true&DisableAppSuggestions=true&DisableWidgets=true&PreventDeviceEncryption=true&VirtIoGuestTools=true&WifiMode=Skip&ExpressSettings=DisableAll&FirstLogonScript1=Enable-WindowsOptionalFeature+-Online+-FeatureName+Microsoft-Hyper-V+-All%3B&FirstLogonScriptType1=Ps1&WdacMode=Skip):

```xml
<RunSynchronousCommand wcm:action="add">
  <Order>24</Order>
  <Path>powershell.exe -NoProfile -Command "Get-Content -LiteralPath '%TEMP%\VirtIoGuestTools.ps1' -Raw | Invoke-Expression;"</Path>

<File path="%TEMP%\VirtIoGuestTools.ps1">
  <!-- etc. -->
</File>
```

On Windows startup a cmd.exe window pops open and asks for an Option "Path" (or similar, this is from the top of my head). The script itself is not run. I believe this is due to a problem with the extraction script, which doesn't properly handle the `%TEMP%` expansion. Manually rewriting the path to `C:\Windows\Setup\Scripts\VirtIoGuestTools.ps1` fixes the problem.

Thanks for this great project!

**Comment by cschneegans** [comment]
Sorry, cannot reproduce. The extraction script uses the `[System.Environment]::ExpandEnvironmentVariables` method to expand environment variables. I don't have a Proxmox environment available right now, but using your exact `autounattend.xml` file on a VMware Windows 10 machine still executes the `VirtIoGuestTools.ps1` script, which outputs  a single line to the `%TEMP%\VirtIoGuestTools.log` file, as expected:

> VirtIO Guest Tools image (virtio-win-*.iso) is not attached to this VM.

Note that the logfile's absolute path is `C:\Windows\Temp\VirtIoGuestTools.log`, not `C:\Users\Admin\AppData\Local\Temp`, and that you need administrative permissions to read it. Does the logfile file exist on your machine?

I admit that using the `%TEMP%` variable might unnecessarily complicate things while having little benefit, so I will consider replacing it with a constant `C:\Windows\Temp` or `C:\Windows\Setup\Scripts` path.

**Comment by cschneegans** [comment]
I have finally moved all script and log files from `C:\Windows\Temp` to `C:\Windows\Setup\Scripts`. This places all relevant files used by the unattended process in a single location, hopefully making debugging easier.

Note that installers run during Windows Setup might still output their logs to `C:\Windows\Temp` (in the same way they output their logs to a user's `%TEMP%` directory when run later by that user).
