### ISSUE TITLE
ultimate performance power plan and hibernation

### ISSUE THREAD

**Issue by procionecurioso** [cschneegans/unattend-generator#2]
Hi, I'm not sure it's possible but I'm wondering if it was possible to add to disable windows hibernation, and enable the ultimate performance power plan by default (also set it as default if possible)

**Comment by cschneegans** [comment]
Consider adding such customizations to the [SetupComplete.cmd](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-a-custom-script-to-windows-setup) file:

```
powercfg.exe /HIBERNATE OFF
powershell.exe -NoProfile -Command "$out=powercfg.exe /DUPLICATESCHEME e9a42b02-d5df-448d-aa00-03f14749eb61;if( $out -match '\s([a-f0-9-]{36})\s'){ powercfg.exe /SETACTIVE $Matches[1];}"
```

The second commands uses PowerShell to extract the GUID returned by the /DUPLICATESCHEME call using a regular expression.
