### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by jon-bit** [cschneegans/unattend-generator#21]
Can we get a section for mainly disabling things related to privacy, such as telemetry, recall, copilot, and more? I'm not a master of Windows, PowerShell, Command Prompt, etc, however, I think a good starting point can be here:

https://github.com/crazy-max/WindowsSpyBlocker

 and here:

 https://github.com/Raphire/Win11Debloat

Also a suggestion, auto-install Chocolaty, Winget, god mode, and other windows fetchers (eg, hyper-v, sandbox, etc)

Also cool site and project. So cool.

**Comment by cschneegans** [comment]
See my [answer on reddit](https://www.reddit.com/r/PowerShell/comments/1dy1psy/comment/lcld7gc/). You should be able to call those tools using the _Run custom scripts_ section. Those tools appear very mature and complete, and I don't think my generator could ever offer all their features.

Regarding package managers, I see in my logfiles that quite a few users install Chocolatey by running the official [installer script](https://docs.chocolatey.org/en-us/choco/setup/) as a custom script. But they typically run their own `choco` commands immediately afterwards, so simply providing a _Install Chocolatey_ checkbox would not be very useful.

**Comment by jon-bit** [comment]
OK, I'll give it a try and get back to you

**Comment by jon-bit** [comment]
OK I slaped this
```
Set-ExecutionPolicy Bypass -Scope Process
& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/"))) -RunDefaults -Silent
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
Install-Script -Name winget-install -Force
```
Into the first custom script option. It did not work (I think, choco is not working at least).

Did I do something wrong? 
Also is their away to get 
```
& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/"))) -RunDefaults -Silent
```
to run without having to enter "Y"

**Comment by cschneegans** [comment]
I ran your script on a Windows 11 VM. It turns out that Chocolatey was successfully installed, but for the System account. Therefore, you probably need to paste the Chocolatey install script in the _Scripts to run when the first user logs_ section instead. The `Install-Script -Name winget-install -Force` statement also seems to throw several errors when it is run as a system script.

The Yes/No/Suspend confirmation question can be avoided by installing the NuGet provider beforehand.

[This link](https://schneegans.de/windows/unattend-generator/?SystemScript0=%26+%28%5Bscriptblock%5D%3A%3ACreate%28%28irm+%22https%3A%2F%2Fwin11debloat.raphi.re%2F%22%29%29%29+-RunDefaults+-Silent%3B%0D%0AInstall-PackageProvider+-Name+NuGet+-MinimumVersion+2.8.5.201+-Force%3B&SystemScriptType0=Ps1&FirstLogonScript0=Set-ExecutionPolicy+Bypass+-Scope+Process+-Force%3B+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+%3D+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+-bor+3072%3B+iex+%28%28New-Object+System.Net.WebClient%29.DownloadString%28%27https%3A%2F%2Fcommunity.chocolatey.org%2Finstall.ps1%27%29%29%3B%0D%0AInstall-Script+-Name+winget-install+-Force%3B&FirstLogonScriptType0=Ps1) will open the form with the necessary modifications to your script.

To analyze possible future problems, check the `C:\Windows\Setup\Scripts\unattend*.log` logfiles.

**Comment by jon-bit** [comment]
OK I'll give it a go and respond soon.

**Comment by jon-bit** [comment]
So I did it but when it starts I still have to press "Y". likeI said I'm not master of powershell but should:

Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force;

be above:

& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/"))) -RunDefaults -Silent;

?

**Comment by jon-bit** [comment]
OK I think I know whats wrong but I have no clue how to fix it. I want a local acout but I am installing this on a vm so I have the link state active or not. How can I install the local acount but still connect to the inter net

If you wondering why I did not notice that before, simple. I'm dumb. (insert face pam)

**Comment by cschneegans** [comment]
You don't need to disconnect your computer from the network. You also don't need to check the _Allow Windows 11 to be installed without internet connection_ setting. Using the autounattend.xml file, you can always create local user accounts even when connected to the Internet.

**Comment by jon-bit** [comment]
OK, but one thing. How would I get this to work on Windows to go? I just tried it and it did not work. It had all the Apps and stuff you don't want when installing windows. Any way to bypass that?

**Comment by cschneegans** [comment]
Sorry, I have zero experience with Windows To Go. It is possible that the generated autounattend.xml works in principle on Windows To Go, but custom scripts are not executed. Custom scripts (which include bloatware removal scripts) rely on the command

`powershell.exe -NoProfile -Command "$xml = [xml]::new(); $xml.Load('C:\Windows\Panther\unattend.xml'); …`

which loads the autounattend.xml itself. With regular installations, this works because a copy is placed at `C:\Windows\Panther\unattend.xml`, but this may not be the case with Windows To Go. Try locating the copy by using a pattern like `*unattend*.xml`.

**Comment by jon-bit** [comment]
Hi sorry for the late replay. Things are crazy lately. Anyway I'm a bit lost on

"With regular installations, this works because a copy is placed at C:\Windows\Panther\unattend.xml, but this may not be the case with Windows To Go. Try locating the copy by using a pattern like *unattend*.xml"

I'm not  big windows person. Can you elaborate? I need some details for This is something I kinda just jumped into.

**Comment by cschneegans** [comment]
To find possible matches, run

`Get-ChildItem -LiteralPath C:\ -Filter *unattend*.xml -ErrorAction SilentlyContinue -Recurse -Force`

in an elevated PowerShell session on the machine that runs Windows To Go.

As far as I understand, .cmd and .bat files behave almost identical. Just try running your scripts as .cmd files.

**Comment by jon-bit** [comment]
OK I'll give it a try but is their any way to run on boot? I made my own iso and I get all the bloat with windows to go (BUT NOT with normal install).

**Comment by cschneegans** [comment]
Note that the command

`Get-ChildItem -LiteralPath C:\ -Filter *unattend*.xml -ErrorAction SilentlyContinue -Recurse -Force`

is only intended for debugging. It will not immediately address the problem. Given that fact that Windows To Go has been discontinued, my own options for debugging are quite limited.

**Comment by jon-bit** [comment]
So ... Their is just no way to run the .xml file on boot on W2G?

**Comment by cschneegans** [comment]
As I said before, I have absolutely no experience with Windows To Go, and I cannot answer that question with certainty. Articles [like this one](https://www.deploymentresearch.com/back-to-basics-automating-the-windows-to-go-setup-windows-8-1-enterprise/) let me assume that Windows To Go does indeed support autounattend.xml files, but I cannot test this. It would really help if you would run the command

`Get-ChildItem -LiteralPath C:\ -Filter *unattend*.xml -ErrorAction SilentlyContinue -Recurse -Force`

in an elevated PowerShell session on a Windows To Go instance.

**Comment by Hammerfest** [comment]
Did some testing as I use Windows2Go on a few of my systems, figured I would give it a test as LTSC 11 is coming out soon so might as well upgrade my old versions when it launches outside OEM.

If you select any of the options after you chose the edition with Rufus, it spawns the unattend.xml file with those options in the C:\Windows\Panther folder which bypasses that which you put in C:\Windows\System32\Sysprep

You will want to manually add in the option from Rufus to prevent auto mounting of internal drives:

<settings pass="offlineServicing">
    <component name="Microsoft-Windows-PartitionManager" processorArchitecture="amd64" language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" publicKeyToken="31bf3856ad364e35" versionScope="nonSxS">
      <SanPolicy>4</SanPolicy>
    </component>
  </settings>




Unrelated, but still annoying: I am running into the same dang issue I had with my ticket cschnegans, everything else seems to run, but apps are not removed and no logs generated, its so fracking weird, its gotta be a 24H2 issue, all my other elections from the autounattend generator happen (sans formatting/version because windows2go), just not apps removed

**Comment by jon-bit** [comment]
Sorry for the late replay. I have been ruining in circles for the past 2 weeks. Anyway That would make seance. I did just base this off of "Apps are still here" look. I apologize but I'm not a master of windows. @Hammerfest , Any way to do this on W2G at all? I just need the apps gone and fire wall blocking IPs. Here is what I have Right now.

https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&Locale=en-US&Keyboard=00000409&GeoLocation=244&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Random&TimeZoneMode=Implicit&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=jon+will&AccountPassword0=password&AccountGroup0=Administrators&AccountName1=&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&ObscurePasswords=true&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=Hidden&ShowFileExtensions=true&DisableWidgets=true&DisableAppSuggestions=true&VBoxGuestAdditions=true&VMwareTools=true&VirtIoGuestTools=true&WifiMode=Interactive&ExpressSettings=DisableAll&Remove3DViewer=true&RemoveBingSearch=true&RemoveCalculator=true&RemoveCamera=true&RemoveClipchamp=true&RemoveClock=true&RemoveCopilot=true&RemoveCortana=true&RemoveDevHome=true&RemoveFamily=true&RemoveFeedbackHub=true&RemoveGetHelp=true&RemoveInternetExplorer=true&RemoveMailCalendar=true&RemoveMaps=true&RemoveMathInputPanel=true&RemoveZuneVideo=true&RemoveNews=true&RemoveNotepadClassic=true&RemoveNotepad=true&RemoveOffice365=true&RemoveOneDrive=true&RemoveOneNote=true&RemoveOpenSSHClient=true&RemoveOutlook=true&RemovePaint=true&RemovePaint3D=true&RemovePeople=true&RemovePhotos=true&RemovePowerAutomate=true&RemovePowerShellISE=true&RemoveQuickAssist=true&RemoveSkype=true&RemoveSnippingTool=true&RemoveSolitaire=true&RemoveStepsRecorder=true&RemoveStickyNotes=true&RemoveTeams=true&RemoveGetStarted=true&RemoveToDo=true&RemoveVoiceRecorder=true&RemoveWeather=true&RemoveWindowsMediaPlayer=true&RemoveZuneMusic=true&RemoveWindowsTerminal=true&RemoveWordPad=true&RemoveXboxApps=true&RemoveYourPhone=true&SystemScript0=%23+Run+the+debloat+script+with+options%0D%0A%26+%28%5Bscriptblock%5D%3A%3ACreate%28%28irm+%22https%3A%2F%2Fwin11debloat.raphi.re%2F%22%29%29%29+-RunDefaults+-Silent+-Sysprep+-RemoveApps+-RemoveCommApps+-RemoveW11Outlook+-RemoveDevApps+-RemoveGamingApps+-ForceRemoveEdge+-DisableDVR+-DisableTelemetry+-DisableBing+-DisableSuggestions+-DisableLockscreenTips+-RevertContextMenu+-ShowHiddenFolders+-ShowKnownFileExt+-HideDupliDrive+-HideSearchTb+-HideTaskview+-HideChat+-DisableWidgets+-DisableCopilot+-DisableRecall+-HideGallery%0D%0A%0D%0A%23+Block+Microsoft+IPs%0D%0A%24urls+%3D+%40%28%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Ffirewall%2Fextra.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Ffirewall%2Fspy.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Ffirewall%2Fupdate.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fextra.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fextra_v6.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fspy.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fspy_v6.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fupdate.txt%22%2C%0D%0A++++%22https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fupdate_v6.txt%22%0D%0A%29%0D%0A%0D%0Aforeach+%28%24url+in+%24urls%29+%7B%0D%0A++++%24content+%3D+%28Invoke-WebRequest+-Uri+%24url+-UseBasicParsing%29.Content%0D%0A++++%24ips+%3D+%24content+-split+%22%60n%22+%7C+Where-Object+%7B%24_+-notmatch+%22%5E%23%22+-and+%24_+-ne+%22%22%7D%0D%0A++++foreach+%28%24ip+in+%24ips%29+%7B%0D%0A++++++++%24ipAddress+%3D+%24ip.Split%28%29%5B0%5D%0D%0A++++++++New-NetFirewallRule+-DisplayName+%22Block+%24ipAddress%22+-Direction+Inbound+-Action+Block+-RemoteAddress+%24ipAddress%0D%0A++++++++New-NetFirewallRule+-DisplayName+%22Block+%24ipAddress%22+-Direction+Outbound+-Action+Block+-RemoteAddress+%24ipAddress%0D%0A++++%7D%0D%0A%7D&SystemScriptType0=Ps1&FirstLogonScript1=%23+Create+God+mode+folder%0D%0A%24godModeFolder+%3D+%22%24env%3AUSERPROFILE%5CDesktop%5CGodMode.%7BED7BA470-8E54-465E-825C-99712043E01C%7D%22%0D%0ANew-Item+-ItemType+Directory+-Path+%24godModeFolder%0D%0A%0D%0A%23+Set+God+mode+folder+icon%0D%0A%24shell+%3D+New-Object+-ComObject+Shell.Application%0D%0A%24folder+%3D+%24shell.Namespace%28%24godModeFolder%29%0D%0A%24folder.Self.Icon+%3D+%22C%3A%5CWindows%5CSystem32%5Cimageres.dll%2C3%22%0D%0A%0D%0A%23+Install+choco+package+provider%0D%0ASet-ExecutionPolicy+Bypass+-Scope+Process+-Force%3B+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+%3D+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+-bor+3072%3B+iex+%28%28New-Object+System.Net.WebClient%29.DownloadString%28%27https%3A%2F%2Fcommunity.chocolatey.org%2Finstall.ps1%27%29%29%0D%0A%0D%0A%23+Create+fast+shutdown+shortcut%0D%0A%24fastShutdownShortcut+%3D+%22%24env%3AUSERPROFILE%5CDesktop%5CFast+Shutdown.lnk%22%0D%0A%24shell+%3D+New-Object+-ComObject+WScript.Shell%0D%0A%24shortcut+%3D+%24shell.CreateShortcut%28%24fastShutdownShortcut%29%0D%0A%24shortcut.TargetPath+%3D+%22C%3A%5CWindows%5CSystem32%5Cshutdown.exe%22%0D%0A%24shortcut.Arguments+%3D+%22%2Fs+%2Ft+0%22%0D%0A%24shortcut.IconLocation+%3D+%22C%3A%5CWindows%5CSystem32%5Cimageres.dll%2C106%22%0D%0A%24shortcut.Description+%3D+%22Fast+Shutdown%22%0D%0A%24shortcut.WorkingDirectory+%3D+%22C%3A%5CWindows%5CSystem32%22%0D%0A%24shortcut.Save%28%29%0D%0A%0D%0A%23+Enable+Hyper-V+and+sandbox+features%0D%0AEnable-WindowsOptionalFeature+-Online+-FeatureName+Microsoft-Hyper-V+-All%0D%0AEnable-WindowsOptionalFeature+-Online+-FeatureName+Containers-DisposableClientVM+-All%0D%0A%0D%0A%23+Configure+DNS+client+to+use+encrypted+DNS%0D%0A%24dnsClient+%3D+Get-DnsClient%0D%0A%24dnsClient.EnableTcpAndUdpFallback+%3D+%24false%0D%0A%24dnsClient.Tls13Fallback+%3D+%24true%0D%0A%24dnsClient.EncryptionMethod+%3D+%22TLS1_2%22%0D%0A%24dnsClient.Save%28%29&FirstLogonScriptType1=Ps1&UserOnceScript0=%23+Create+God+mode+folder%0D%0A%24godModeFolder+%3D+%22%24env%3AUSERPROFILE%5CDesktop%5CGodMode.%7BED7BA470-8E54-465E-825C-99712043E01C%7D%22%0D%0ANew-Item+-ItemType+Directory+-Path+%24godModeFolder%0D%0A%0D%0A%23+Set+God+mode+folder+icon%0D%0A%24shell+%3D+New-Object+-ComObject+Shell.Application%0D%0A%24folder+%3D+%24shell.Namespace%28%24godModeFolder%29%0D%0A%24folder.Self.Icon+%3D+%22C%3A%5CWindows%5CSystem32%5Cimageres.dll%2C3%22%0D%0A%0D%0A%23+Install+choco+package+provider%0D%0ASet-ExecutionPolicy+Bypass+-Scope+Process+-Force%3B+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+%3D+%5BSystem.Net.ServicePointManager%5D%3A%3ASecurityProtocol+-bor+3072%3B+iex+%28%28New-Object+System.Net.WebClient%29.DownloadString%28%27https%3A%2F%2Fcommunity.chocolatey.org%2Finstall.ps1%27%29%29%0D%0A%0D%0A%23+Create+fast+shutdown+shortcut%0D%0A%24fastShutdownShortcut+%3D+%22%24env%3AUSERPROFILE%5CDesktop%5CFast+Shutdown.lnk%22%0D%0A%24shell+%3D+New-Object+-ComObject+WScript.Shell%0D%0A%24shortcut+%3D+%24shell.CreateShortcut%28%24fastShutdownShortcut%29%0D%0A%24shortcut.TargetPath+%3D+%22C%3A%5CWindows%5CSystem32%5Cshutdown.exe%22%0D%0A%24shortcut.Arguments+%3D+%22%2Fs+%2Ft+0%22%0D%0A%24shortcut.IconLocation+%3D+%22C%3A%5CWindows%5CSystem32%5Cimageres.dll%2C106%22%0D%0A%24shortcut.Description+%3D+%22Fast+Shutdown%22%0D%0A%24shortcut.WorkingDirectory+%3D+%22C%3A%5CWindows%5CSystem32%22%0D%0A%24shortcut.Save%28%29%0D%0A%0D%0A%23+Enable+Hyper-V+and+sandbox+features%0D%0AEnable-WindowsOptionalFeature+-Online+-FeatureName+Microsoft-Hyper-V+-All%0D%0AEnable-WindowsOptionalFeature+-Online+-FeatureName+Containers-DisposableClientVM+-All%0D%0A%0D%0A%23+Configure+DNS+client+to+use+encrypted+DNS%0D%0A%24dnsClient+%3D+Get-DnsClient%0D%0A%24dnsClient.EnableTcpAndUdpFallback+%3D+%24false%0D%0A%24dnsClient.Tls13Fallback+%3D+%24true%0D%0A%24dnsClient.EncryptionMethod+%3D+%22TLS1_2%22%0D%0A%24dnsClient.Save%28%29&UserOnceScriptType0=Ps1&WdacMode=Skip

**Comment by jon-bit** [comment]
I'm going to test Windows 2 go again. I'll let everyone know how it went. I'll be a bit however. Might be Friday before the update.
