### ISSUE TITLE
[FEATURE] Add Option for disabling fast startup (win10/win11)

### ISSUE THREAD

**Issue by MisterT87** [cschneegans/unattend-generator#24]
Hey, is it possible to add a option to disable fast startup on windows 10/11 ?

Fast Startup comes from old win8 times, ssds werent standard as boot drives...
IF your boot drive is a SSD -> disable fast startup and ohterwise not (if no SSD)

Fast Startup: Prevents windows 10/11 users to clean shutdown (ram will be saved to disk and recovered on reboot) (even RAM errors will be saved also)
and SSD users only save around 2 seconds with fast startup enabled

AND btw thanks for your generator, it helps alot ! :)

**Comment by cschneegans** [comment]
You can easily add a .reg file

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power]
"HiberbootEnabled"=dword:00000000
```

in the _Scripts to run in the system context_ section. This [link](https://schneegans.de/windows/unattend-generator/?SystemScript0=%5BHKEY_LOCAL_MACHINE%5CSYSTEM%5CCurrentControlSet%5CControl%5CSession+Manager%5CPower%5D%0D%0A%22HiberbootEnabled%22%3Ddword%3A00000000&SystemScriptType0=Reg) will configure the form accordingly.

**Comment by MisterT87** [comment]
Thanks!
Can I leave it open to add an option, or do you think no option will be added ?

**Comment by cschneegans** [comment]
This registry setting is so straightforward that I don't think it justifies an option in the generator UI, sorry.

**Comment by MisterT87** [comment]
Ok true :)
Just asking and again thanks for good work! :)

**Comment by cschneegans** [comment]
I totally forgot that I had indeed added (via https://github.com/cschneegans/unattend-generator/commit/4e6b0223a7e73ecc2980ec90b96edaead2f8b09e) a dedicated setting for this:

![image](https://github.com/user-attachments/assets/d9fd95eb-8f4c-4f76-b64c-d0b8370d101d)
