### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tayvermtos** [cschneegans/unattend-generator#25]
Hi

Firstly thanks so much for this extremely handy tool! 

Do You think it would be possible to add to the generator the following 2 Options:
1. Show file extensions
2. Show hidden files in file explorer

Thanks a lot!

**Comment by cschneegans** [comment]
This can be achieved by adding a custom .reg file in the _Scripts to run whenever a user logs on for the first time_ section:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Hidden"=dword:00000001
"HideFileExt"=dword:00000000
```

This registry setting is quite straightforward, so I don't think it justifies an option in the generator UI.

**Comment by cschneegans** [comment]
After repeated requests, I have now added those settings via https://github.com/cschneegans/unattend-generator/commit/e0554aeece582b2ce36342923c7dd0222f2b2000. Hence, a custom script is no longer necessary. Check out the new _Windows Explorer tweaks_ section in the [web UI](https://schneegans.de/windows/unattend-generator/).
