### ISSUE TITLE
Start pins are cleared after each restart.

### ISSUE THREAD

**Issue by jNizM** [cschneegans/unattend-generator#26]
Moin,

kann es sein, dass diese StartPins Einstellungen ("HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\Start") dafür sorgen, dass jedesmal nach dem Neustart alle manuell gesetzten StartPins wieder entfernen?

------------------------

Hi there,

Is it possible that these StartPins settings (‘HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\Start’) ensure that all manually set StartPins are removed each time after a restart?

**Comment by cschneegans** [comment]
Cannot reproduce. Testing with an original `Win11_23H2_English_x64v2.iso` image and an `autounattend.xml` file that removes most bloatware components. When a user logs on for the first time, there are no shortcuts in the **Pinned** section of the Start menu as expected (and only the _Get Started_ shortcut in the **Recommended** section).

Nevertheless, adding shortcuts (via the _Pin to Start_ command) works, and those shortcuts remain after a restart.
