### ISSUE TITLE
[FEATURE_REQUEST] New registry settings for unattend-generator

### ISSUE THREAD

**Issue by deffcolony** [cschneegans/unattend-generator#27]
I would like to request the addition of the following registry settings to the unattended Windows setup generator available at https://schneegans.de/windows/unattend-generator/. These settings would help customize the taskbar, explorer, and desktop experience.

```xml
<!-- [TASKBAR] Task View button (0 = Hide)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "ShowTaskViewButton" /t REG_DWORD /d 0 /f

<!-- [TASKBAR] Set alignment to Left (0 = Left) -->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "TaskbarAl" /t REG_DWORD /d 0 /f

<!-- [TASKBAR] widgets  (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "TaskbarDa" /t REG_DWORD /d 0 /f

<!-- [TASKBAR] Copilot button on taskbar (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "ShowCopilotButton" /t REG_DWORD /d 0 /f

<!-- [TASKBAR] Search box (0 = Hide)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Search" /v "SearchboxTaskbarMode" /t REG_DWORD /d 0 /f

<!-- [EXPLORER] Show file extensions for known file types (0 = Enable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "HideFileExt" /t REG_DWORD /d 0 /f

<!-- [EXPLORER] Compact view for items (1 = Enable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "UseCompactMode" /t REG_DWORD /d 1 /f

<!-- [EXPLORER] Bing Search in start menu (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Search" /v "BingSearchEnabled" /t REG_DWORD /d 0 /f

<!-- [DESKTOP] Show "This PC" icon (0 = Enable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f

<!-- [TASKBAR] Disable App Launch Tracking for all users (1 = Enable)-->
reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Windows\EdgeUI" /v "DisableMFUTracking" /t REG_DWORD /d 1 /f

<!-- [SUGGESTIONS] Show recommendations for tips, shortcuts, new apps, and more in start (0 = Disable) -->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "Start_IrisRecommendations" /t REG_DWORD /d 0 /f

<!-- [SUGGESTIONS] Suggest ways I can finish setting up my device to get the most out of Windows (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v "ScoobeSystemSettingEnabled" /t REG_DWORD /d 0 /f

<!-- [SUGGESTIONS] Sync provider ads (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "ShowSyncProviderNotifications" /t REG_DWORD /d 0 /f

<!-- [SUGGESTIONS] "Suggested" app notifications (Ads for MS services) (0 = Disable)-->
reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.Suggested" /v "Enabled" /t REG_DWORD /d 0 /f
```

**Comment by cschneegans** [comment]
Added a setting to control how to display the search box in the taskbar in #59.

**Comment by kzshantonu** [comment]
May I suggest:

```bat
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v LaunchTo /t REG_DWORD /d 1 /f
```

Opens explorer to This PC.

Plenty of Windows users I know including myself who love using Win+E immediately set this by hand after fresh install anyway.

Also personal curiosity: I don't understand the reluctance to add new checkboxes to the website. It's not like there are any defaults. The user have to select everything they want anyway. I don't see why having more options is a bad thing. It's just a text based website.

I say this as a huge fan. I use it so much I even created my own short url for it: mni dot li slash wug

**Comment by lxwulf** [comment]
+1 to @kzshantonu request!

**Comment by Tolqua** [comment]
After creating a new VM using a Schneegans autounattend file, the first thing I notice after initial boot is the desktop with a plain background (as per my specification).  The next thing I always do is change the desktop icon settings (right-click menu on Desktop):  
- View > Small icons
- View > Auto arrange icons
- Sort by > Date modified *

This keeps things neat and minimal which is one of the main aims of a customised install and I'd like to see these options added as checkbox options so that they apply to the default user profile and all users' desktops start off like this.   

* One problem with the 'Sort by > Date modified' setting is that there's no way to explicitly specify the sort order.  This means that when I do this manually I have to make the same selection twice to give an ascending sort that keeps the Recycle bin icon in the top-left corner.

**Comment by deffcolony** [comment]
I would like to request the addition of the following new registry settings This is copied from the original Command Store command: Windows.CompressTo used in the new windows 11 update 24H2

It adds a new context menu item to the old windows context menu called "compress to":

```reg
<!-- [EXPLORER] Add "Compress to ZIP File" to old context menu for files -->
reg.exe add "HKEY_CLASSES_ROOT\*\shell\CompressToFullMenu_ForOldContextMenu" /v "CommandStateSync" /t REG_SZ /d "" /f
reg.exe add "HKEY_CLASSES_ROOT\*\shell\CompressToFullMenu_ForOldContextMenu" /v "ExplorerCommandHandler" /t REG_SZ /d "{7AE6900F-6EB0-44A2-9CA1-DB2F7EF352AF}" /f
reg.exe add "HKEY_CLASSES_ROOT\*\shell\CompressToFullMenu_ForOldContextMenu" /v "MUIVerb" /t REG_SZ /d "@Windows.UI.FileExplorer.dll,-51797" /f

<!-- [EXPLORER] Add "Compress to ZIP File" to old context menu for folders -->
reg.exe add "HKEY_CLASSES_ROOT\Folder\shell\CompressToFullMenu_ForOldContextMenu" /v "CommandStateSync" /t REG_SZ /d "" /f
reg.exe add "HKEY_CLASSES_ROOT\Folder\shell\CompressToFullMenu_ForOldContextMenu" /v "ExplorerCommandHandler" /t REG_SZ /d "{7AE6900F-6EB0-44A2-9CA1-DB2F7EF352AF}" /f
reg.exe add "HKEY_CLASSES_ROOT\Folder\shell\CompressToFullMenu_ForOldContextMenu" /v "MUIVerb" /t REG_SZ /d "@Windows.UI.FileExplorer.dll,-51797" /f
```

**Comment by mawi5276** [comment]
Why not using the Run custom scripts part?

Not everyone wants your customizations...

**Comment by Tolqua** [comment]
Running custom scripts is fine if you know what you're doing, but the whole point of a utility like this is to offer options to non-technical users who know what they want, but either lack the technical know-how to achieve it, or simply appreciate a simpler procedure.  

...and they are 'options' after all, so if you don't want 'em, don't select 'em.

**Comment by deffcolony** [comment]
@mawi5276 You can’t speak for everyone. Just because you personally don't want certain customizations doesn't mean others feel the same. The fact that you're dismissing all custom requests indicates that perhaps this tool doesn't meet your needs, and that's okay But it’s clear that others do find value in these customizations, which is why they are being requested. If the tool doesn't fit your specific use case, maybe it's worth exploring other solutions that are a better match for you.

**Comment by cschneegans** [comment]
> Opens explorer to This PC.

Now added via https://github.com/cschneegans/unattend-generator/commit/dcf3ea46feb5aa82b562c4531f1a4475f57ce0bf:

![image](https://github.com/user-attachments/assets/13155845-4519-4b2d-8784-e74cf36e1974)

That commit also refactored how _RunOnce_ commands are executed, i.e. commands that run when a user logs on for the first time. Previously, you might have seen multiple PowerShell windows popping up. All _RunOnce_ commands (including those provided by custom scripts) are now run from a single PowerShell process. Furthermore, output from these commands is collected in `%TEMP%\UserOnce.log` for debugging purposes.

**Comment by stimpy81** [comment]
> @mawi5276 You can’t speak for everyone. Just because you personally don't want certain customizations doesn't mean others feel the same. The fact that you're dismissing all custom requests indicates that perhaps this tool doesn't meet your needs, and that's okay But it’s clear that others do find value in these customizations, which is why they are being requested. If the tool doesn't fit your specific use case, maybe it's worth exploring other solutions that are a better match for you.

He's absolutely right.  I can't stand gatekeeping like this.  After all, what exactly would be the point of a service like this in the first place, after all, we could all just hand write our own autounattend scripts, couldn't we?

**Comment by stimpy81** [comment]
> @mawi5276 You can’t speak for everyone. Just because you personally don't want certain customizations doesn't mean others feel the same. The fact that you're dismissing all custom requests indicates that perhaps this tool doesn't meet your needs, and that's okay But it’s clear that others do find value in these customizations, which is why they are being requested. If the tool doesn't fit your specific use case, maybe it's worth exploring other solutions that are a better match for you.

Absolutely correct, I cannot stand gatekeepers like this.  There would be absolutely no point for this service to exist because we can all just hand write our own autounattend scripts...

**Comment by cschneegans** [comment]
> ```
> 
> ```

Now added via https://github.com/cschneegans/unattend-generator/commit/216a247ea8235d1ff55158a107468de4891ee0e9:

![image](https://github.com/user-attachments/assets/947a075c-b1dc-4fba-a039-eeb858882e6d)

**Comment by kzshantonu** [comment]
Thanks for the new additions <3
