### ISSUE TITLE
Request feature: The option to use manifest V2 in Chromium Browsers.

### ISSUE THREAD

**Issue by Mxfuuu** [cschneegans/unattend-generator#33]
The following to the registry should allow a user to use Extensions that are dependent on manifest V2:
reg add HKLM\Software\Policies\Google\Chrome /v ExtensionManifestV2Availability /t REG_DWORD /d 2 /f

The following should help with other Chromium browsers as well:

reg add HKLM\Software\Policies\Microsoft\Edge /v ExtensionManifestV2Availability /t REG_DWORD /d 2 /f

reg add HKLM\Software\Policies\Policies\Vivaldi /v ExtensionManifestV2Availability /t REG_DWORD /d 2 /f

Most users would love to have the option to add this in their .xml file.

**Comment by cschneegans** [comment]
Given the fact that these registry keys target third-party programs, I feel reluctant to add a dedicated option.

I think it is more appropriate to use a custom script for this – can easily add your commands to the _Scripts to run in the system context, before user accounts are created_ section, either as a .cmd file 

`reg add HKLM\Software\Policies\Google\Chrome /v ExtensionManifestV2Availability /t REG_DWORD /d 2 /f`

or a .reg file

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExtensionManifestV2Availability"=dword:00000002
```
