### ISSUE TITLE
Include the latest cumulative update in install iso and debloat

### ISSUE THREAD

**Issue by XerXes777** [cschneegans/unattend-generator#37]
You wrote: Bloatware removal works best with the original Windows 10 and 11 .iso images downloaded from Microsoft.
I did not perform any tests with custom images.

It is okay to include the latest cumulative update with "Add-WindowsPackage" in install.wim?
And use your debloat settings.

**Comment by cschneegans** [comment]
If you only apply Windows Update packages to your install.wim, you will probably be fine. Other modifications (like removal of provisioned packages) are more risky.

**Comment by cschneegans** [comment]
An alternative might be to apply the .msu updates via `Add-WindowsPackage -Online` during the autounattend.xml process. Managing reboots might be tricky, though.
