### ISSUE TITLE
Disable 8.3 Naming

### ISSUE THREAD

**Issue by ChGen** [cschneegans/unattend-generator#39]
I see you that you included the tweak on disabling access times support on NTFS for performance reasons. I suggest you add another tweak, Disable 8.3 Naming, which could also improve NTFS performance with multiple small files (basically most of msys/cygwin/git/python stuff). See also this link for details and performance graph: https://learn.microsoft.com/ru-ru/archive/blogs/josebda/windows-server-2012-file-server-tip-disable-8-3-naming-and-strip-those-short-names-too

**Comment by cschneegans** [comment]
I am aware of the [many problems](https://schneegans.de/windows/no-8.3/) with 8.3 names – the performance impact is not even the most serious, IMO.

Ideally, I would like to not only disable 8.3 name creation, but get rid of all 8.3 names, including the notorious `PROGRA~1`. It is very appealing to do this in the PE phase of Windows Setup, before Windows boots for the first time, but combining this with the autounattend.xml process is challenging.

In the meantime, consider using a custom script to call `fsutil.exe 8dot3name set C: 1`. [This URL](https://schneegans.de/windows/unattend-generator/?SystemScript0=fsutil.exe+8dot3name+set+C%3A+1&SystemScriptType0=Cmd) will configure the form accordingly.

**Comment by inschrift-spruch-raum** [comment]
I saw the following registration form on a [Chinese forum](https://www.cnblogs.com/suv789/p/18062365)
![image](https://github.com/user-attachments/assets/7429a68f-328b-4439-ba0a-1d7710def197)
Try this one
](https://www.cnblogs.com/suv789/p/18062365)

**Comment by cschneegans** [comment]
Disabling 8.3 name creation is simple and does not even require editing the registry – just run `fsutil.exe 8dot3name set 1` or `fsutil.exe 8dot3name set C: 1`. But this does not address the problem that at this point there are already about 80,000 file names on the C: drive.

**Comment by cschneegans** [comment]
In my opinion, by far the best opportunity to remove 8.3 names is before Windows has even started for the first time. This leaves two approaches:

- Strip 8.3 names from the install.wim image by [following these instructions](https://schneegans.de/windows/no-8.3/#wim).
- Strip 8.3 names in the Windows PE phase of Windows Setup by [following these instructions](https://schneegans.de/windows/no-8.3/#setup). To make this work and still use an answer file, I have recently added a new setting:

![image](https://github.com/user-attachments/assets/13043295-23fa-472a-8158-c60c2427c28e)

Assuming the answer file is located on `D:\`, run this command to begin the installation: 

```
setup.exe /NoReboot /Unattend:D:\notautounattend.xml
```

Unfortunately, I don't see a way to fully automate this – you still have to run those `fsutil.exe` commands before Windows starts for the first time.

**Comment by inschrift-spruch-raum** [comment]
> Disabling 8.3 name creation is simple and does not even require editing the registry – just run `fsutil.exe 8dot3name set 1` or `fsutil.exe 8dot3name set C: 1`. But this does not address the problem that at this point there are already about 80,000 8.3 file names on the C: drive.

Perhaps this is another bug in my NTLite encapsulation, my ISO image cannot execute this command
