### ISSUE TITLE
[request] option to tell windows that hardware clock is UTC time

### ISSUE THREAD

**Issue by kzshantonu** [cschneegans/unattend-generator#43]
Useful for people who will dual boot Linux later

**Comment by cschneegans** [comment]
I use the

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
"RealTimeIsUniversal"=dword:00000001
```

registry value myself, but I don't think it justifies a dedicated setting in the generator. Please use a custom script instead.
