### ISSUE TITLE
Feature Request: Relocate user folders (Desktop, Documents, Downloads, Music Pictures, Videos) to another drive (e.g., D:)

### ISSUE THREAD

**Issue by hafizullahchishti** [cschneegans/unattend-generator#46]
To simplify backups and general navigation, I like to relocate most of the user folders to the root of D: (and delete the others such as Favorites, Searches, 3D Objects, Contacts, etc.).

I understand there's a way using the answer file to do this, but I haven't been able to find much information about it. I did create a dskpart script to partition the drive at the outset, and this works in cschneegans's answer file. 

I have in the past used the Location tab in each folder's Properties to relocate them one-at-a-time post install, but I like the idea of Setup putting them in the right place from the start.

**Comment by cschneegans** [comment]
I have never moved my user profiles from `C:\Users` to another location, and I don't see much benefit in doing so.

However, _if_ you want to store your user profiles on another drive, setting this up via an autounattend.xml file is probably a good approach as this allows you to apply the required modifications early, i.e. before user accounts are even created.

Therefore, you could try the following:

1. Use a custom diskpart script (in the _Partitioning and formatting_ section) to create the Windows partition and a data partition.
2. Use one of the following methods:
    - Generate and download your autounattend.xml file, locate the `Microsoft-Windows-Shell-Setup` component and add a [ProfilesDirectory](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-folderlocations-profilesdirectory) element.
    - Use a .reg file in the _Scripts to run in the system context, before user accounts are created_ section to modify the ProfilesDirectory value in both keys `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList]` and `[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\ProfileList]`.

I have not tested this. Also note Microsoft warning from the link above: “We don’t recommend using this setting, except perhaps in a test environment.”

**Comment by cschneegans** [comment]
I have now tried to make this work using a .cmd script that runs “before user accounts are created”:

```
mkdir D:\Users
reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList" /v ProfilesDirectory /t REG_SZ /d "D:\Users" /f
reg.exe add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\ProfileList" /v ProfilesDirectory /t REG_SZ /d "D:\Users" /f
```

[This link](https://schneegans.de/windows/unattend-generator/?SystemScript0=mkdir+D%3A%5CUsers%0D%0Areg.exe+add+%22HKLM%5CSOFTWARE%5CMicrosoft%5CWindows+NT%5CCurrentVersion%5CProfileList%22+%2Fv+ProfilesDirectory+%2Ft+REG_SZ+%2Fd+%22D%3A%5CUsers%22+%2Ff%0D%0Areg.exe+add+%22HKLM%5CSOFTWARE%5CWOW6432Node%5CMicrosoft%5CWindows+NT%5CCurrentVersion%5CProfileList%22+%2Fv+ProfilesDirectory+%2Ft+REG_SZ+%2Fd+%22D%3A%5CUsers%22+%2Ff&SystemScriptType0=Cmd) will configure the form accordingly. Works for me – the profiles for all users are created under `D:\Users`. I still advise against this.
