### ISSUE TITLE
encrypt the password

### ISSUE THREAD

**Issue by wellsyu** [cschneegans/unattend-generator#47]
i found that the password of users is plain text, if one can get the iso ,he can get the password.
so,can this generator provide the password encrypted

**Comment by stimpy81** [comment]
> i found that the password of users is plain text, if one can get the iso ,he can get the password. so,can this generator provide the password encrypted

Simply click the option to **Obscure all account passwords in your autounattend.xml file with Base64**

**Comment by cschneegans** [comment]
> Simply click the option to **Obscure all account passwords in your autounattend.xml file with Base64** located in the User Accounts section.

Yes, but note that this is not a proper encryption. An attacker will still be able to read the passwords, albeit with a little more effort.
