### ISSUE TITLE
CTT utility cannot run

### ISSUE THREAD

**Issue by chrisnitro2000** [cschneegans/unattend-generator#48]
Amazing works you have done but I have an issue , after clean installation I cannot use the CTT utility that runs scripts to further debloat the os. It’s like when it’s starts powershell it ends the process immediately and says tweaks are finished . According to CTT forums this happens because something is blocking the powershell commands to be executed . Any ideas ? When I was creatigg by the xml file so choose all different options and u til now I made 4-5 new windows 11 installations without any luck .

**Comment by cschneegans** [comment]
I am not aware of fundamental problems. [Memory’s Tech Tips](https://github.com/memstechtips/UnattendedWinstall) even runs CTT as part of an unattended setup. _Allow execution of PowerShell script files_ should probably be set in the form. Besides that, I would expect that CTT writes a log file somewhere.

**Comment by chrisnitro2000** [comment]
I think the powershell policy that is applied by default is RemoteSigned whatever you do to change it .

**Comment by chrisnitro2000** [comment]
Also there is bug at the moment from the CTT utility side . Thanks a lot for your effort anyway .
