### ISSUE TITLE
xbox app removal process problem

### ISSUE THREAD

**Issue by procionecurioso** [cschneegans/unattend-generator#49]
When you remove the xbox apps with the unattend file, if you open a game you get a pop up I think because the gamebar is missing in the pc, I tried to solve by disabling from regedit the overlay capture part as written on a post on reddit but it doesn't work. Here is the pop up
![aoac5six9ftb1](https://github.com/user-attachments/assets/50ee18b0-8ec2-41e9-ac98-267c058967f3)

**Comment by cschneegans** [comment]
Well, I am not a gamer, and I am not familiar with all these Xbox services. I can indeed reproduce the issue when I download and run Microsoft's _Solitaire & Casual Games_ app from the store. 

As you suggested, I tried to suppress the pop-up by adding some registry values according to [this Reddit post by AveYo](https://www.reddit.com/r/Windows11/comments/vm046d/comment/ie0j6o3/). Without stderr and stdout redirection, the commands look like this:

```
reg.exe add HKCR\ms-gamebar /f /ve /d URL:ms-gamebar
reg.exe add HKCR\ms-gamebar /f /v "URL Protocol" /d ""
reg.exe add HKCR\ms-gamebar /f /v "NoOpenWith" /d ""
reg.exe add HKCR\ms-gamebar\shell\open\command /f /ve /d "C:\Windows\System32\systray.exe"
reg.exe add HKCR\ms-gamebarservices /f /ve /d URL:ms-gamebarservices
reg.exe add HKCR\ms-gamebarservices /f /v "URL Protocol" /d ""
reg.exe add HKCR\ms-gamebarservices /f /v "NoOpenWith" /d ""
reg.exe add HKCR\ms-gamebarservices\shell\open\command /f /ve /d "C:\Windows\System32\systray.exe"
```

Such commands can easily be run by adding them in the _Scripts to run in the system context_ section of my form. But unfortunately, they just don't work for me, i.e. the annoying pop-up still appears.

Furthermore, when I install the Xbox app, it immediately complains about missing dependencies:

![image](https://github.com/user-attachments/assets/5b24f4b6-d144-4bd3-baaa-e04670b6024f)

![image](https://github.com/user-attachments/assets/e5bd1c8b-d936-4bb8-9b79-8cd251ad17a1)

If you intend to use Xbox services, it is probably best not to select the _Xbox Apps_ components for removal in the first place.
