### ISSUE TITLE
Invalid Specialize Pass When Using Custom Scripts

### ISSUE THREAD

**Issue by SuperJC710e** [cschneegans/unattend-generator#5]
First of all, thanks for this awesome resource! It's been very useful! :)

I'm testing out the new addition of the Custom Script options. However, as soon as I add in one or more scripts, it breaks the answer file. The initial setup phases complete, but then it errors out complaining about an invalid specialize pass. Here's a screenshot:

![image](https://github.com/cschneegans/unattend-generator/assets/13032430/530a1d6f-1598-4ded-9147-249ad24e8089)

I've now tested this one without any scripts, and the answer file still works fine as usual.  However in testing once in a Windows 11 23H2 with 2 script sections (both powershell), and then with Windows 10 22H2 with a single powershell script section it fails with the above error. I'm including a URL to that most recent answer file.

URL: [autounattend.xml](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&UserLocale=en-CA&KeyboardLayout=1009%3A00001009&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Random&TimeZoneMode=Explicit&TimeZone=Eastern+Standard+Time&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=SysAdmin&AccountPassword0=password&AccountGroup0=Administrators&AccountName1=SysUser&AccountPassword1=password&AccountGroup1=Users&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&EnableLongPaths=true&EnableRemoteDesktop=true&AllowPowerShellScripts=true&DisableLastAccess=true&TurnOffSystemSounds=true&RunScriptOnFirstLogon=true&DisableAppSuggestions=true&DisableWidgets=true&WifiMode=Skip&ExpressSettings=DisableAll&Remove3DViewer=true&RemoveCamera=true&RemoveClipchamp=true&RemoveCortana=true&RemoveDevHome=true&RemoveFamily=true&RemoveFeedbackHub=true&RemoveGetHelp=true&RemoveInternetExplorer=true&RemoveMailCalendar=true&RemoveMaps=true&RemoveMathInputPanel=true&RemoveZuneVideo=true&RemoveNews=true&RemoveOffice365=true&RemoveOneDrive=true&RemoveOneNote=true&RemoveOutlook=true&RemovePaint=true&RemovePaint3D=true&RemovePeople=true&RemovePhotos=true&RemovePowerAutomate=true&RemovePowerShellISE=true&RemoveQuickAssist=true&RemoveSkype=true&RemoveSnippingTool=true&RemoveSolitaire=true&RemoveStepsRecorder=true&RemoveTeams=true&RemoveGetStarted=true&RemoveToDo=true&RemoveVoiceRecorder=true&RemoveWeather=true&RemoveWindowsMediaPlayer=true&RemoveZuneMusic=true&RemoveWordPad=true&RemoveXboxApps=true&RemoveYourPhone=true&SystemScriptType=Cmd&SystemScript=&FirstLogonScriptType=Cmd&FirstLogonScript=&UserOnceScriptType=Ps1&UserOnceScript=if+%28-NOT+%28Test-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27%29%29+{+New-Item+-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27+-Force+|+Out-Null+}+%0D%0ANew-ItemProperty+-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27+-Name+%27SystemUsesLightTheme%27+-Value+0+-PropertyType+DWORD+-Force%0D%0Aif+%28-NOT+%28Test-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27%29%29+{+New-Item+-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27+-Force+|+Out-Null+}+%0D%0ANew-ItemProperty+-Path+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27+-Name+%27AppsUseLightTheme%27+-Value+0+-PropertyType+DWORD+-Force%0D%0Aif+%28%28Test-Path+-LiteralPath+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CSearch%27%29+-ne+%24true%29+{+New-Item+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CSearch%27+-force+-ea+SilentlyContinue+}%0D%0ANew-ItemProperty+-LiteralPath+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CSearch%27+-Name+%27SearchboxTaskbarMode%27+-Value+0+-PropertyType+DWord+-Force+-ea+SilentlyContinue%0D%0Aif+%28%28Test-Path+-LiteralPath+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CMultiTaskingView%5CAllUpView%27%29+-ne+%24true%29+{+Remove-Item+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CMultiTaskingView%5CAllUpView%27+-force+-ea+SilentlyContinue+}%0D%0Aif+%28%28Test-Path+-LiteralPath+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CAdvanced%27%29+-ne+%24true%29+{+New-Item+%27HKLM%3A%5CSOFTWARE%5CPolicies%5CMicrosoft%5CWindows%5CWindows+Search%27+-force+-ea+SilentlyContinue+}%0D%0ANew-ItemProperty+-LiteralPath+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CAdvanced%27+-Name+%27ShowTaskViewButton%27+-Value+0+-PropertyType+DWord+-Force+-ea+SilentlyContinue%0D%0A&WdacMode=Skip)

I had to look up what was going on with the `<nul set /p=` section of the redirection. I see it's useful to prevent newlines and the `<nul` prevents it from asking for input. However, I wonder if it's then setting the errorlevel to 1 as in these [answers](https://stackoverflow.com/a/11336754) and that is causing the setup to think there is an error? (Totally not my area of knowledge, so I could be way out in left field...)

Anyway, hopefully we can find a fix for this. Thanks in advance! :)

**Comment by SuperJC710e** [comment]
An update, I recreated the script section with shortened lines which avoided any of the `<nul set /p =` redirection, however, the error still occurred, so it must be something else that is causing it.

URL: [autounattend.xml](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&UserLocale=en-CA&KeyboardLayout=1009%3A00001009&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Random&TimeZoneMode=Explicit&TimeZone=Eastern+Standard+Time&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=SysAdmin&AccountPassword0=password&AccountGroup0=Administrators&AccountName1=SysUser&AccountPassword1=password&AccountGroup1=Users&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&EnableLongPaths=true&EnableRemoteDesktop=true&AllowPowerShellScripts=true&DisableLastAccess=true&TurnOffSystemSounds=true&RunScriptOnFirstLogon=true&DisableAppSuggestions=true&DisableWidgets=true&WifiMode=Skip&ExpressSettings=DisableAll&Remove3DViewer=true&RemoveCamera=true&RemoveClipchamp=true&RemoveCortana=true&RemoveDevHome=true&RemoveFamily=true&RemoveFeedbackHub=true&RemoveGetHelp=true&RemoveInternetExplorer=true&RemoveMailCalendar=true&RemoveMaps=true&RemoveMathInputPanel=true&RemoveZuneVideo=true&RemoveNews=true&RemoveOffice365=true&RemoveOneDrive=true&RemoveOneNote=true&RemoveOutlook=true&RemovePaint=true&RemovePaint3D=true&RemovePeople=true&RemovePhotos=true&RemovePowerAutomate=true&RemovePowerShellISE=true&RemoveQuickAssist=true&RemoveSkype=true&RemoveSnippingTool=true&RemoveSolitaire=true&RemoveStepsRecorder=true&RemoveTeams=true&RemoveGetStarted=true&RemoveToDo=true&RemoveVoiceRecorder=true&RemoveWeather=true&RemoveWindowsMediaPlayer=true&RemoveZuneMusic=true&RemoveWordPad=true&RemoveXboxApps=true&RemoveYourPhone=true&SystemScriptType=Cmd&SystemScript=&FirstLogonScriptType=Cmd&FirstLogonScript=&UserOnceScriptType=Ps1&UserOnceScript=%24RegPath1+%3D+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CThemes%5CPersonalize%27%0D%0A%24RegItem1a+%3D+%27SystemUsesLightTheme%27%0D%0A%24RegItem1b+%3D+%27AppsUseLightTheme%27%0D%0Aif+%28-NOT%28Test-Path+%24RegPath1%29%29%7BNew-Item+-Path+%24RegPath1+-Force%7COut-Null%7D%0D%0ANew-ItemProperty+-Path+%24RegPath1+-Name+%24RegItem1a+-Value+0+-PropertyType+DWORD+-Force%0D%0Aif+%28-NOT%28Test-Path+%24RegPath1%29%29+%7BNew-Item+-Path+%24RegPath1+-Force%7COut-Null%7D%0D%0ANew-ItemProperty+-Path+%24RegPath1+-Name+%24RegItem1b+-Value+0+-PropertyType+DWORD+-Force%0D%0A%24RegPath2+%3D+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CSearch%27%0D%0A%24RegItem2a+%3D+%27SearchboxTaskbarMode%27%0D%0Aif+%28-NOT%28Test-Path+-Path+%24RegPath2%29%29+%7BNew-Item+%24RegPath2+-Force%7D%0D%0ANew-ItemProperty+-Path+%24RegPath2+-Name+%24RegItem2a+-Value+0+-PropertyType+DWord+-Force%0D%0A%24RegPath3+%3D+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CMultiTaskingView%5CAllUpView%27%0D%0Aif+%28-NOT%28Test-Path+-Path+%24RegPath3%29%29+%7BRemove-Item+%24RegPath3+-Force%7D%0D%0A%24RegPath4+%3D+%27HKCU%3A%5CSoftware%5CMicrosoft%5CWindows%5CCurrentVersion%5CExplorer%5CAdvanced%27%0D%0A%24RegItem4a+%3D+%27ShowTaskViewButton%27%0D%0Aif+%28-NOT%28Test-Path+-Path+%24RegPath4%29%29+%7BNew-Item+%24RegPath4+-Force%7D%0D%0ANew-ItemProperty+-Path+%24RegPath4+-Name+%24RegItem4a+-Value+0+-PropertyType+DWord+-Force%0D%0A&WdacMode=Skip)

Here's the script I included in the "Run these commands whenever a user logs on for the first time" section (I reduced a couple more spaces in this one...):

```shell
$RegPath1 = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
$RegItem1a = 'SystemUsesLightTheme'
$RegItem1b = 'AppsUseLightTheme'
if (-NOT(Test-Path $RegPath1)){New-Item -Path $RegPath1 -Force|Out-Null}
New-ItemProperty -Path $RegPath1 -Name $RegItem1a -Value 0 -PropertyType DWORD -Force
if (-NOT(Test-Path $RegPath1)){New-Item -Path $RegPath1 -Force|Out-Null}
New-ItemProperty -Path $RegPath1 -Name $RegItem1b -Value 0 -PropertyType DWORD -Force
$RegPath2 = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Search'
$RegItem2a = 'SearchboxTaskbarMode'
if (-NOT(Test-Path -Path $RegPath2)){New-Item $RegPath2 -Force}
New-ItemProperty -Path $RegPath2 -Name $RegItem2a -Value 0 -PropertyType DWord -Force
$RegPath3 = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\MultiTaskingView\AllUpView'
if (Test-Path -Path $RegPath3){Remove-Item $RegPath3 -Force}
$RegPath4 = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
$RegItem4a = 'ShowTaskViewButton'
if (-NOT(Test-Path -Path $RegPath4)){New-Item $RegPath4 -Force}
New-ItemProperty -Path $RegPath4 -Name $RegItem4a -Value 0 -PropertyType DWord -Force
```

**Comment by cschneegans** [comment]
The problem was that the command `reg.exe add "HKU\mount\Software\Microsoft\Windows\CurrentVersion\Runonce" /v "C:\Windows\Setup\Scripts\unattend-01" /t REG_SZ /d "powershell.exe …` became longer than 256 characters, and this happened because the registry value name was erroneously set to `C:\Windows\Setup\Scripts\unattend-01`, while the intended value name is simply `unattend-01`.

This has now been corrected via https://github.com/cschneegans/unattend-generator/commit/5fb224bfc56d74a7b6a7de373189377bbfc9279b. Thanks for your report!

**Comment by SuperJC710e** [comment]
Thanks Christoph, I'll test it out. Also, good to know about the 256 character limitation, I think I knew that somewhere in the deep recesses of my mind, but good to have that memory refreshed! 👍 

**Update**: So I did test it out. The answer file works fine, however, the script itself is not created. Do we perhaps need to create the `Scripts` directory first? I think `C:\Windows\Setup` exists by default, but not the `Scripts` sub-directory.

**Comment by cschneegans** [comment]
> The answer file works fine, however, the script itself is not created. Do we perhaps need to create the `Scripts` directory first? I think `C:\Windows\Setup` exists by default, but not the `Scripts` sub-directory.

You are exactly correct. I didn't notice because I had previously added the `…\Scripts\Setup\SetupComplete.cmd` file to all my Windows images. Fixed via https://github.com/cschneegans/unattend-generator/commit/4d546f1df0c53fbf3dcbdd06aeffd2517e083d09.

**Comment by SuperJC710e** [comment]
Yay! It's working now! (Some of my customizations aren't working, but that's not a fault of this!) Many thanks! Great work! :) 

PS: I noticed one small thing with the URL in the comments....it doesn't seem to preserve the setting for the Keyboard Layout selected. For instance I usually select "English (Canada)" which sets the Keyboard Layout to "Canadian French" by default. I generally change that to "United States - English". However, when I use the URL from the answer file, the keyboard layout reverts to the default (Canadian French). Just a small niggle...

**Comment by cschneegans** [comment]
> PS: I noticed one small thing with the URL in the comments....it doesn't seem to preserve the setting for the Keyboard Layout selected. For instance I usually select "English (Canada)" which sets the Keyboard Layout to "Canadian French" by default. I generally change that to "United States - English". However, when I use the URL from the answer file, the keyboard layout reverts to the default (Canadian French).

Correct again. If a user locale has an associated keyboard layout, that layout was selected unconditionally. The new behavior is to keep the keyboard layout when one is present in the _KeyboardLayout_ query string parameter.

**Comment by SuperJC710e** [comment]
> > PS: I noticed one small thing with the URL in the comments....it doesn't seem to preserve the setting for the Keyboard Layout selected. For instance I usually select "English (Canada)" which sets the Keyboard Layout to "Canadian French" by default. I generally change that to "United States - English". However, when I use the URL from the answer file, the keyboard layout reverts to the default (Canadian French).
> 
> Correct again. If a user locale has an associated keyboard layout, that layout was selected unconditionally. The new behavior is to keep the keyboard layout when one is present in the _KeyboardLayout_ query string parameter.

Excellent! Once again, thanks so much for your excellent work! I'll close this issue now! 👍
