### ISSUE TITLE
[FEATURE_REQUEST] Change variable locations

### ISSUE THREAD

**Issue by erwannmag** [cschneegans/unattend-generator#51]
Would it be possible to move default variables locations to custom ones, i.e.:

"C:\Users\John Doe\Documents" 

to

"D:\Documents"

And doing this for the others such as Desktop, Music, Images, Downloads, etc.

**Comment by cschneegans** [comment]
Duplicate of https://github.com/cschneegans/unattend-generator/issues/46. I have provided a custom script there that performs this modification during Setup. Microsoft strongly advises against relocating the profiles directory.
