### ISSUE TITLE
how to skip update when network connected

### ISSUE THREAD

**Issue by wellsyu** [cschneegans/unattend-generator#54]
i tried to install win11_23h2 when network connected , it cost much time,
if disconnect network, it will be fast
![win11_updating](https://github.com/user-attachments/assets/caa2171f-29d7-46f0-852d-b20e799a6bb0)

**Comment by cschneegans** [comment]
Sorry, I don't know if there is a setting for that. [DynamicUpdate](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-dynamicupdate) sounds promising, but it only applies to the PE phase of Windows Setup, while your screenshot is clearly from a later stage of Windows Setup.
