### ISSUE TITLE
[REQUEST] Detect partition style

### ISSUE THREAD

**Issue by d6hlkgoczv** [cschneegans/unattend-generator#58]
I'm trying to automate the partitioning but we can only choose between MBR and GPT. I was thinking we could have a powershell script to detect if disk is currently MBR or GPT and then use the specific settings for each one, something like this:

```
$disk = Get-Disk -Number 0
if ($disk.PartitionStyle -eq "GPT") {
    diskpart.exe /s X:\gpt_diskpart.txt
}
else ($disk.PartitionStyle -eq "MBR") {
    diskpart.exe /s X:\mbr_diskpart.txt
}
```

Basically I wanted to do what the windows setup does when we interact with partition, we can't really choose GPT or MBR in the UI. Since I have older PCs with MBR and newer ones with GPT, it'd be better to have a single .iso that detects the partition style instead of having 2 different ones for each

**Comment by cschneegans** [comment]
PowerShell is not available in Windows PE.

You can distinguish between BIOS and UEFI systems in [Windows PE](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/wpeutil-command-line-options?view=windows-11#updatebootinfo) by running `wpeutil UpdateBootInfo` and then examining the `PEFirmwareType` value in the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control` registry key, using `reg.exe` or `cscript.exe`. Note that BIOS systems always use MBR partitioning, while UEFI systems always use GPT partitioning.

However, I doubt that there are many users that would need such a feature.

**Comment by d6hlkgoczv** [comment]
I'll try to do that, thanks!
And about if users need that feature, I mean, it's an automated process, why wouldn't users want that? They won't have to worry about creating an unattend file for BIOS or UEFI, it'll be handled automatically... I think there's no cons in that.
But anyway, thank you for clearing that up, I didn't know PowerShell wasn't available in Windows PE, I came from NTLite so there's some things I still don't know what to do, like creating a random computer name with a custom handle, like DESKTOP-randomNumber, in NTLite it let's me create with another name, for example Company-randomNumber using a * in the ComputerName but setting a FullName in Windows PE, however it didn't work when I modified the unattend file for some reason.

**Comment by cschneegans** [comment]
> And about if users need that feature, I mean, it's an automated process, why wouldn't users want that? They won't have to worry about creating an unattend file for BIOS or UEFI, it'll be handled automatically... I think there's no cons in that.

- The UI would probably get more complicated.
- Parsing the output of `reg.exe query HKLM\System\CurrentControlSet\Control /v PEFirmwareType` is not trivial.
- BIOS/MBR is getting more and more obsolete. 

> But anyway, thank you for clearing that up, I didn't know PowerShell wasn't available in Windows PE, I came from NTLite so there's some things I still don't know how to do, like creating a random computer name with a custom handle, like DESKTOP-randomNumber, in NTLite it let's me create with another name, for example Company-randomNumber using a * in the ComputerName but setting a FullName in Windows PE, however it didn't work when I modified the unattend file for some reason.

I [didn't manage](https://github.com/cschneegans/unattend-generator/issues/45) to set a computer name _during_ Windows Setup, but you can add a custom script that runs “when the first user logs on after Windows has been installed”.

**Comment by d6hlkgoczv** [comment]
We have fewer and fewer BIOS/MBR machines now, the goal is to replace them all. But until that happens, we still have to use them, so it would be good to have this. I'll look into it. And about the computer name thing, I already have a custom script to change the name after, just wanted to know if it'd be possible to do during the setup. Thanks!

**Comment by cschneegans** [comment]
> And about the computer name thing, I already have a custom script to change the name after, just wanted to know if it'd be possible to do during the setup. Thanks!

Just added a new setting **Provide a PowerShell script to set the computer name dynamically**, which you may find interesting:

![image](https://github.com/user-attachments/assets/f8ab5500-7481-46bc-ac44-0d3e3af1cc4b)

**Comment by d6hlkgoczv** [comment]
just wanted to tell you you're doing gods work with this project, thank you!
