### ISSUE TITLE
[REQUEST] How to have only 2 requests during the installation phase

### ISSUE THREAD

**Issue by Victory61** [cschneegans/unattend-generator#62]
Good morning
I generated the response file and it is all OK, without any request during the installation.
I wanted to ask how to modify the obtained xml file in such a way that during the installation I get only 2 requests:
 Username and Password.
Thank you very much

`<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">

	
	
	<settings pass="offlineServicing"></settings>
	<settings pass="windowsPE">
	
		<component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
			<SetupUILanguage>
				<UILanguage>it-IT</UILanguage>
			</SetupUILanguage>
			<InputLocale>0410:00000410</InputLocale>
			<SystemLocale>it-IT</SystemLocale>
			<UILanguage>it-IT</UILanguage>
			<UserLocale>it-IT</UserLocale>
		</component>
		
		<component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
			<UserData>
				<ProductKey>
					<Key>VK7JG-NPHTM-C97JM-9MPGT-3V66T</Key>
				</ProductKey>
				<AcceptEula>true</AcceptEula>
			</UserData>
			<RunSynchronous>
				<RunSynchronousCommand wcm:action="add">
					<Order>1</Order>
					<Path>reg.exe add "HKLM\SYSTEM\Setup\LabConfig" /v BypassTPMCheck /t REG_DWORD /d 1 /f</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>2</Order>
					<Path>reg.exe add "HKLM\SYSTEM\Setup\LabConfig" /v BypassSecureBootCheck /t REG_DWORD /d 1 /f</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>3</Order>
					<Path>reg.exe add "HKLM\SYSTEM\Setup\LabConfig" /v BypassRAMCheck /t REG_DWORD /d 1 /f</Path>
				</RunSynchronousCommand>
			</RunSynchronous>
		</component>
		</settings>
		
	<settings pass="generalize"></settings>
	<settings pass="specialize">
		<component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
			<RunSynchronous>
				<RunSynchronousCommand wcm:action="add">
					<Order>1</Order>
					<Path>reg.exe add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE" /v BypassNRO /t REG_DWORD /d 1 /f</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>2</Order>
					<Path>net.exe accounts /maxpwage:UNLIMITED</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>3</Order>
					<Path>reg.exe load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT"</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>4</Order>
					<Path>reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "HideFileExt" /t REG_DWORD /d 0 /f</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>5</Order>
					<Path>reg.exe unload "HKU\DefaultUser"</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>6</Order>
					<Path>reg.exe load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT"</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>7</Order>
					<Path>reg.exe add "HKU\DefaultUser\Software\Microsoft\Windows\CurrentVersion\RunOnce" /v "SearchboxTaskbarMode" /t REG_SZ /d "reg.exe add HKCU\Software\Microsoft\Windows\CurrentVersion\Search /v SearchboxTaskbarMode /t REG_DWORD /d 2 /f" /f</Path>
				</RunSynchronousCommand>
				<RunSynchronousCommand wcm:action="add">
					<Order>8</Order>
					<Path>reg.exe unload "HKU\DefaultUser"</Path>
				</RunSynchronousCommand>
			</RunSynchronous>
		</component>
	</settings>
	
	
	<settings pass="auditSystem"></settings>
	<settings pass="auditUser"></settings>
	<settings pass="oobeSystem">
		<component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
			<InputLocale>0410:00000410</InputLocale>
			<SystemLocale>it-IT</SystemLocale>
			<UILanguage>it-IT</UILanguage>
			<UserLocale>it-IT</UserLocale>
		</component>
		<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
			<UserAccounts>
				<LocalAccounts>
					<LocalAccount wcm:action="add">
						<Name>Admin</Name>
						<Group>Administrators</Group>
						<Password>
							<Value>password</Value>
							<PlainText>true</PlainText>
						</Password>
					</LocalAccount>
					<LocalAccount wcm:action="add">
						<Name>User</Name>
						<Group>Users</Group>
						<Password>
							<Value>password</Value>
							<PlainText>true</PlainText>
						</Password>
					</LocalAccount>
				</LocalAccounts>
			</UserAccounts>
			<AutoLogon>
				<Username>Admin</Username>
				<Enabled>true</Enabled>
				<LogonCount>1</LogonCount>
				<Password>
					<Value>password</Value>
					<PlainText>true</PlainText>
				</Password>
			</AutoLogon>
	
	
			<OOBE>
				<ProtectYourPC>3</ProtectYourPC>
				<HideEULAPage>true</HideEULAPage>
				<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
			</OOBE>
			
			<FirstLogonCommands>
				<SynchronousCommand wcm:action="add">
					<Order>1</Order>
					<CommandLine>reg.exe add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoLogonCount /t REG_DWORD /d 0 /f</CommandLine>
				</SynchronousCommand>
			</FirstLogonCommands>
		</component>
	</settings>
	
</unattend>`

**Comment by cschneegans** [comment]
There is no built-in support for setting username and password dynamically.

I would try the following: Let Windows Setup enable the “Administrator” account and don't create any other accounts:

![image](https://github.com/user-attachments/assets/9acb5645-345e-4da7-9ca3-6213c7ebfd23)

Then add a custom .ps1 script to run “when the first user logs on after Windows has been installed”, like so:

```
$username = Read-Host -Prompt 'Enter username';
$password = Read-Host -Prompt 'Enter password';
New-LocalUser -Name $username -Password( ConvertTo-SecureString -String $password -AsPlainText -Force ) -AccountNeverExpires -PasswordNeverExpires;
Get-LocalUser -Name Administrator | Disable-LocalUser
```

I have not tested this.

**Comment by Victory61** [comment]
Thank you for the suggestion.
In the 23H2 version I always have the script I attach, in the 24H2 version it doesn't work and I don't know how to modify it.
This only allows the two requests for Username and Password.
`

<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    
    
    <settings pass="windowsPE">
        <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetupUILanguage>
                <UILanguage>it-IT</UILanguage>
            </SetupUILanguage>
            <InputLocale>it-IT</InputLocale>
            <SystemLocale>it-IT</SystemLocale>
            <UILanguage>it-IT</UILanguage>
            <UserLocale>it-IT</UserLocale>
        </component>
        <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ImageInstall>
                <OSImage>
                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/INDEX</Key>
                            <Value>1</Value>
                        </MetaData>
                    </InstallFrom>
                </OSImage>
            </ImageInstall>
            <UserData>
                <AcceptEula>true</AcceptEula>
            </UserData>
        </component>
    </settings>
        
    
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <InputLocale>it-IT</InputLocale>
            <SystemLocale>it-IT</SystemLocale>
            <UILanguage>it-IT</UILanguage>
            <UserLocale>it-IT</UserLocale>
        </component>
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <ProtectYourPC>3</ProtectYourPC>
            </OOBE>             
         </component>  
         <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="x86" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <FirstLogonCommands>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>CMD /c REG.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v "ScoobeSystemSettingEnabled" /t REG_DWORD /d 0 /f</CommandLine>
                    <Description>Disable OOBE Screen - Get even more out of Windows</Description>
                    <Order>1</Order>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>CMD /c REG.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System" /v "AllowCrossDeviceClipboard" /t REG_DWORD /d 0 /f</CommandLine>
                    <Description>Disable OOBE Screen - Synchronize the activities</Description>
                    <Order>2</Order>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>CMD /c REG.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System" /v "EnableActivityFeed" /t REG_DWORD /d 0 /f</CommandLine>
                    <Description>Disable OOBE Screen - Synchronize the activities</Description>
                    <Order>3</Order>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>CMD /c REG.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System" /v "PublishUserActivities" /t REG_DWORD /d 0 /f</CommandLine>
                    <Description>Disable OOBE Screen - Synchronize the activities</Description>
                    <Order>4</Order>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>CMD /c REG.exe add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System" /v "UploadUserActivities" /t REG_DWORD /d 0 /f</CommandLine>
                    <Description>Disable OOBE Screen - Synchronize the activities</Description>
                    <Order>5</Order>
                </SynchronousCommand>
            </FirstLogonCommands>      
        </component>
     </settings>
</unattend>
`

**Comment by kzshantonu** [comment]
@Victory61 if you use ventoy, you can use `$$VARNAME$$`. Ventoy will then ask you to type whatever you want into those variables. 

https://www.ventoy.net/en/plugin_autoinstall.html

**Comment by cschneegans** [comment]
> https://justpaste.it/du8ml

That file has no `<UserAccounts>` elements, hence Windows Setup will ask for the username. You can easily achieve this result when you select this setting:

![image](https://github.com/user-attachments/assets/257d4901-c527-4840-86d8-aae5bdc36587)

However, while 23H2 let you create a local account, 24H2 practically forces you to create a Microsoft account.

**Comment by Victory61** [comment]
> @Victory61 se usi ventoy, puoi usare `$$VARNAME$$`. Ventoy ti chiederà quindi di digitare quello che vuoi in quelle variabili.
> 
> [https://www.ventoy.net/en/plugin_autoinstall.html ](https://www.ventoy.net/en/plugin_autoinstall.html)

Gazie for the suggestion.
I am not familiar with this procedure, I will try to figure out how to get the two requests.

**Comment by Victory61** [comment]
> Non esiste un supporto integrato per l'impostazione dinamica di nome utente e password.
> 
> Vorrei provare quanto segue: consentire all'installazione di Windows di abilitare l'account "Amministratore" e non creare altri account:
> 

> Quindi aggiungi uno script .ps1 personalizzato da eseguire "quando il primo utente accede dopo l'installazione di Windows", in questo modo:
> 
> ```
> $username = Read-Host -Prompt 'Enter username';
> $password = Read-Host -Prompt 'Enter password';
> New-LocalUser -Name $username -Password( ConvertTo-SecureString -String $password -AsPlainText -Force ) -AccountNeverExpires -PasswordNeverExpires;
> Get-LocalUser -Name Administrator | Disable-LocalUser
> ```
> 
> Non l'ho testato.

Very interesting, I don't know how to use this script in xml file

**Comment by Victory61** [comment]
@cschneegans 
Did I do well in this way?
![Immagine 2024-10-03 180031](https://github.com/user-attachments/assets/841bc705-c9be-4dc7-96c0-68fb0f5d77fc)

**Comment by Victory61** [comment]
@cschneegans
![Immagine 2024-10-03 180031](https://github.com/user-attachments/assets/af7e88b2-3215-423a-8ac0-9be708eda266)

Did I do well in this way?

**Comment by cschneegans** [comment]
I just re-examined the `autounattend.xml` you posted earlier, which sets both the _**Let Windows Setup create the following local (“offline”) accounts**_ and the _**Let Windows generate a random computer name like DESKTOP-ZFAH8Z2**_ options. Therefore, you should not see any of the dialogs from the screenshots you posted.

This is very similar to #63 – which .iso image did you use?

**Comment by Victory61** [comment]
I downloaded the ISO from Media Creation Tool 24H2b26100.1742

**Comment by Victory61** [comment]
I finally succeeded.
I made a change to the generated script by inserting blocks from the old script and I get the durations requested and can also enter audit mode.

https://justpaste.it/gucsx

**Comment by Victory61** [comment]
Good morning.
Even inserting the file created by the generator I get the same error, I tried not inserting any autounattend file and the installation was successful, obviously with all the requirements. 
So I assume the incompatibility is created by the autounattend file after the procedure with sys prep.
