### ISSUE TITLE
windows 24H2

### ISSUE THREAD

**Issue by liviodaina** [cschneegans/unattend-generator#63]
- on windows 24H2 computer name assignement is asked even if specified as assigned automatically DEKSTOP-??????
- on windows 24H2 ask for ad join computer or account online

- same file xml works fine on 23H2
thanks

**Comment by liviodaina** [comment]
[autounattend_xml.txt](https://github.com/user-attachments/files/17242989/autounattend_xml.txt)

![1](https://github.com/user-attachments/assets/45a2c6c7-5ee3-4f85-ae2d-17192a75d70e)
![2](https://github.com/user-attachments/assets/e7290ef4-9619-4a83-befb-69e84c47fa46)
![3](https://github.com/user-attachments/assets/09748cf0-030c-44b2-a2ed-6c0f89483942)

Message:
"
i attach the file autounattend.xml that works correclty with win11(23H2), no problem perfect
the same file autounattend.xml doesnt work with win11(24h2)
for the iso i've used the one downloaded from Microsoft license portal site with official version licensed, relased official 24H2 on 02 oct 2024
- the fist image 01.jpg ask for computername: "Assegna un nome al dispositivo" -> "Assign a name to your device"
- the second image 02.jpg ask for login with microsoft account or other option to use local account or next active directory join
- the third image 03.jpg "Configurazione per uso personale" -> "Configure for personal use" /// "Configura per l'uso aziendale o dell'istituto di istruzione" -> "Configure for organizational usage"
thanks for your support.
regards, livio.
"

**Comment by cschneegans** [comment]
I used your `autounattend.xml` file with the official `Win11_24H2_Italian_x64.iso` image [downloaded from Microsoft](https://www.microsoft.com/en-us/software-download/windows11), and the installation ran without interruption from start to finish. When you see any dialogs during the installation process, I assume this must be due to the .iso image you used.

**Comment by liviodaina** [comment]
thanks, for your support i will try and i give you a feedback

**Comment by liviodaina** [comment]
Hi,

> I used your `autounattend.xml` file with the official `Win11_24H2_Italian_x64.iso` image [downloaded from Microsoft](https://www.microsoft.com/en-us/software-download/windows11), and the installation ran without interruption from start to finish. When you see any dialogs during the installation process, I assume this must be due to the .iso image you used.

Hi,
you are rigth, there was a mistake on building a usb key with rufus, now i've rebuild the usb key with rufus and no other option checked and it's works.
sorry for my error!
regards, livio
