### ISSUE TITLE
windows 11 24h2, and september update of 23H2 ask for language

### ISSUE THREAD

**Issue by peroptica** [cschneegans/unattend-generator#64]
windows 11 24h2, and september update of 23H2 ask for language on first screen

Settings are English, Croatia, Standard

**Comment by cschneegans** [comment]
When this happens it is usually because the selected **Windows display language** does not match the language of your .iso file:

![image](https://github.com/user-attachments/assets/4e8b955a-6619-45bb-9ec9-d1e0209d4911)

**Comment by peroptica** [comment]
if i add this
<UILanguageFallback>en-US</UILanguageFallback>

it works

**Comment by cschneegans** [comment]
Interesting. In my experiments, `UILanguageFallback` never had any  effect.

So I assume you had the Windows display language set to Croatian, used the Win11_24H2_Croatian_x64.iso image, added `<UILanguageFallback>en-US</UILanguageFallback>` to your autounattend.xml file, and Windows Setup would no longer display this dialog?

![image](https://github.com/user-attachments/assets/76141194-2c5c-4635-9e35-7bc6eacb2d63)

**Comment by peroptica** [comment]
i userd 24h2 English (not international) version, that fallback solves my problem
