### ISSUE TITLE
[FEATURE_REQUEST] Compact mode image install option

### ISSUE THREAD

**Issue by eugenesan** [cschneegans/unattend-generator#65]
I wonder why there is no option to enable compact mode image install mode.
It goes as follows:
```
<component name="Microsoft-Windows-Setup" ...>
<ImageInstall>
<OSImage>
<Compact>true</Compact>
</OSImage>
</ImageInstall>
</components>
```
It should be an equivalent of:
```
dism /apply-image /imagefile:d:\sources\install.wim /index:1 /applydir:c:\ /compact
```
This can improve performance in situations where storage is slow and/or limited and should also reduce RAM usage.
This option in unattended.xml  seems to be working on Tiny11 and similar mods.

P.S.
To avoid confusion, in older versions of Windows compact mode was special mode when the whole OS image was executed directly from .WIM but in recent releases it just compresses the system files on disk during image application.

**Comment by cschneegans** [comment]
I will check this out, but [Microsoft's documentation](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-imageinstall-osimage) does not mention the `<Compact>` element. How did you learn about this element?

**Comment by eugenesan** [comment]
> I will check this out, but [Microsoft's documentation](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-imageinstall-osimage) does not mention the `<Compact>` element. How did you learn about this element?

I believe that's where I saw it first: https://github.com/ntdevlabs/tiny11builder/blob/48714d253f77ea8d778949cc25244ab9083c21bd/autounattend.xml#L20C22-L20C29

I did some "experimenting" since I opened this issue and it seems like the new installer in 24H2 is capable of enabling compact mode automatically but I could not figure under what conditions.
On real hardware (i5-Gen11/8GB) it tends to enable it but on VM (i5-Gen6/3GB) it tends to disable it claiming "Windows has determined that compact mode is not beneficiary for that system" when checking using `compact /compactos:query`.
Regardless, the flag seems to work when Windows is not "against" it.

Unrelated to the "issue", I've noticed a few changes with the final 24H2:
1. Legacy installer no longer an option like it was in previous builds
2. The new setup.exe is not accepting any parameters and I couldn't find a way to stop/replace it like with the legacy installer.  `Download settings:` section of your website might need a warning about that.
3. Ventoy doesn't support 24H2 (https://github.com/ventoy/Ventoy/issues/2887)

Seems like the new installer changed quite a few things without documenting it.
But with general reduction in size of 24H2 and thanks to your unattend-generator (with minor tweaks from https://github.com/memstechtips/UnattendedWinstall/blob/main/IoT-LTSC-Like/autounattend.xml) I was able to achieve results comparable to Tiny11 without "kneecapping" the system.
Base system is only ~11GB and base RAM usage is around ~2GB.

**Comment by cschneegans** [comment]
Added new setting to select Compact OS behavior:

![image](https://github.com/user-attachments/assets/1d68c545-acb8-4164-bdc2-e2ef7be22d42)

**Comment by eugenesan** [comment]
Excellent!
Thanks.

BTW,
It seems like "Previous setup version" is available after all on 24H2.
It's just not always shown: https://github.com/ventoy/Ventoy/issues/2887#issuecomment-2395244731

**Comment by eugenesan** [comment]
I just tested the new option and I don't think it's working.
Except the commented URL+Variables part, resulting .xml doesn't change regardless of which of the 3 options is chosen.

**Comment by cschneegans** [comment]
Shoot, you are correct. This happened in conjunction with the **Partition the disk interactively during Windows Setup** setting, because in that case I simply deleted the entire 

```
<ImageInstall>
	<OSImage>
		<Compact>…</Compact>
		<InstallTo>
			<DiskID>…</DiskID>
			<PartitionID>…</PartitionID>
		</InstallTo>
	</OSImage>
</ImageInstall>
```

element from the XML document, which also deleted the new `<Compact>…</Compact>` element.

Fixed now via https://github.com/cschneegans/unattend-generator/commit/ddf94d9ad6a9dd185b43f35f99ef1ac913db2b4d.
