### ISSUE TITLE
Request - Offline account.

### ISSUE THREAD

**Issue by kendi182** [cschneegans/unattend-generator#71]
![Captura de tela 2024-10-09 105445](https://github.com/user-attachments/assets/64f37e2f-2da8-482e-b79a-7723a2c560d9) 

I used the command below to create an offline account without the need to request an account online.

it prompts when installing Windows.
Could you add this option?

```<OOBE>
<ProtectYourPC>3</ProtectYourPC>
<HideEULAPage>true</HideEULAPage>
<HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>
<NetworkLocation>Home</NetworkLocation>
<SkipUserOOBE>false</SkipUserOOBE>
<SkipMachineOOBE>false</SkipMachineOOBE>
<HideOnlineAccountScreens>true</HideOnlineAccountScreens>
</OOBE>

**Comment by cschneegans** [comment]
Interesting, I was not aware about this setting. Now added via https://github.com/cschneegans/unattend-generator/commit/7a577e15c56c859b83825d4d00eafcaa862a28c3. Seems to work with both Windows 10 and Windows 11.

![image](https://github.com/user-attachments/assets/f5ad4666-a8d7-422f-bacc-9aa4312c3d8e)

With this setting, 24H2 will download updates during setup, and even lets you play a game?!

![image](https://github.com/user-attachments/assets/1d596f51-d073-4dcb-83ee-d4917edb60cf)
