### ISSUE TITLE
Request - Pull bios serial or ask to choose version

### ISSUE THREAD

**Issue by kendi182** [cschneegans/unattend-generator#72]
It could include this option if the bios does not contain the windows serial and install automatically, make Windows provide the option to choose a version available in the image.
![Captura de tela 2024-10-09 110106](https://github.com/user-attachments/assets/016f203c-4c43-40ce-88e1-a4d8b58f26bb)

```
<ProductKey>
<WillShowUI>Always</WillShowUI>
</ProductKey>

**Comment by cschneegans** [comment]
What is the use case here? If you select **Enter your own product key during Windows Setup** and then click **I don't have a product key**, you will be presented with a list of available images:

![image](https://github.com/user-attachments/assets/077eb797-cbdb-4108-86f3-7ae256db9aaa)

Also, I wouldn't even know how to implement this. Note that all this takes place in Windows PE, so PowerShell is not available.
