### ISSUE TITLE
Request - Dynamic Device naming

### ISSUE THREAD

**Issue by hipsoppel** [cschneegans/unattend-generator#73]
Would it be possible to setup dynamic naming in the base unattend file without the use of custom scripts section.   For an example, make the computer name dependent of variables pulled from BIOs keys ie serial or asset tag.    Doing it through scripts is possible but cumbersome due the requirement of restarting the device before the name is set. 

I also might just be missing a simple solution otherwise

**Comment by cschneegans** [comment]
I would love to provide a mechanism to set the computer name _during_ Windows Setup. That sounds simple enough, but I have been [unsuccessful so far](https://github.com/cschneegans/unattend-generator/issues/45#issuecomment-2328399635).

Calling `Rename-Computer` in a script placed in the _Scripts to run when the first user logs on after Windows has been installed_ section works reliably – but as you have noted in #70, this will require another reboot.

**Comment by cschneegans** [comment]
Just added a new setting **Provide a PowerShell script to set the computer name dynamically**, which you may find interesting:

![image](https://github.com/user-attachments/assets/fe79495b-fd27-4277-a755-19f3f010e092)

**Comment by hipsoppel** [comment]
Awesome! Thanks a ton. This is working almost perfectly. My only follow up is about the character limit.  The current logic I have written is about 2500-3000 characters. Could the limit of 999 be increased ?

**Comment by cschneegans** [comment]
There is no length limit for any of the textarea inputs. The only limitation is that the resulting URL must not be longer than 64k characters, as this is the limit for the .NET `System.Uri` class, which I employ.
