### ISSUE TITLE
REQUEST - memstechtips IoT-LTSC-Like

### ISSUE THREAD

**Issue by kendi182** [cschneegans/unattend-generator#77]
hello,
Is it possible to include the following commands in your script generator?

```
:: Hides Task View Button on Taskbar
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowTaskViewButton /t REG_DWORD /d 0 /f
```

```
:: Set Registry Keys to Enable End Task With Right Click
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarDeveloperSettings /t REG_DWORD /d 1 /f
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarEndTask /t REG_DWORD /d 1 /f
```

```
# Enables .NET Framework 3.5
  DISM /Online /Enable-Feature /FeatureName:NetFx3 /All /Source:X:\sources\sxs /LimitAccess
```

```
# Enable the Ultimate Performance power plan
  powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61

```

**Comment by mawi5276** [comment]
You can do it by yourself in the "Run custom scripts"  Part

**Comment by cschneegans** [comment]
> DISM /Online /Enable-Feature /FeatureName:NetFx3 /All /Source:X:\sources\sxs /LimitAccess

Well, that's a first. Usually people want me to remove/disable/uninstall Windows components. 🤔

Why do you want to enable .NET Framework 3.5?

**Comment by cschneegans** [comment]
> :: Hides Task View Button on Taskbar
> reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowTaskViewButton /t REG_DWORD /d 0 /f

Now added via https://github.com/cschneegans/unattend-generator/commit/216a247ea8235d1ff55158a107468de4891ee0e9:

![image](https://github.com/user-attachments/assets/c358bf21-9b63-4911-af81-9416e149c4fc)

**Comment by cschneegans** [comment]
> :: Set Registry Keys to Enable End Task With Right Click
> reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarDeveloperSettings /t REG_DWORD /d 1 /f
> reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarEndTask /t REG_DWORD /d 1 /f

That command should read

```
reg.exe add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings" /v TaskbarEndTask /t REG_DWORD /d 1 /f
```

instead.

To be honest, I have never missed the _End task_ command, since _Close window_ does the same thing in almost all cases.

**Comment by kendi182** [comment]
> > DISM /Online /Enable-Feature /FeatureName:NetFx3 /All /Source:X:\sources\sxs /LimitAccess
> 
> Well, that's a first. Usually people want me to remove/disable/uninstall Windows components. 🤔
> 
> Why do you want to enable .NET Framework 3.5?

because in uup when creating the iso they offer the option to activate net 3.5.

**Comment by kendi182** [comment]
good morning!
Thanks for including.
I have some more suggestions


```# Ativar historico de area de transferencia
Set-ItemProperty -Path "HKCU:\Software\Microsoft\Clipboard" -Name "EnableClipboardHistory" -Value 1 -Type DWord

# Ativar “Obter atualizacoes assim que disponiveis” no Windows Update
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" -Name "IsContinuousInnovationOptedIn" -Value 1```

![image](https://github.com/user-attachments/assets/af683754-1abc-4c11-b628-05f6fb27ea6e)
