### ISSUE TITLE
[!] 8.3 File Name Removal Instructions

### ISSUE THREAD

**Issue by Hammerfest** [cschneegans/unattend-generator#78]
Running the script results in no actions, sadly no logs or anything in event viewer either.
https://schneegans.de/windows/no-8.3/#wim

I took install.wim, the ps1 script, and psexec, put them in the folder structure mentioned as well as E:\z\ for good measure.
Simply goes to next line if run in bundled PowerShell, or asks about security then goes to new line in newer PowerShell.

"
PS C:\iso\sources> .\Remove-WimShortNames -WimFile 'C:\iso\sources\install.wim';
PS C:\iso\sources> .\Remove-WimShortNames -WimFile 'C:\iso\sources\install.wim';

or 

PS C:\iso\sources> .\Remove-WimShortNames -WimFile 'C:\iso\sources\install.wim';

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\iso\sources\Remove-WimShortNames.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
PS C:\iso\sources>
"

I did also run unblock-file to get rid of the security warning in new PowerShell and it returns the same behavior as old PowerShell
EDIT: I also checked the script and changed the $PsExecPath to the same dir, the path in the script doesn't seem to exist as there is no installer for the tools, the windows store installer also doesn't put it there

**Comment by cschneegans** [comment]
> PS C:\iso\sources> .\Remove-WimShortNames -WimFile 'C:\iso\sources\install.wim';

1) You first have to execute the function definition. The idea is to copy the entire function definition to the clipboard and paste it in a PowerShell window. Alternatively, you can download the .ps1 file with your browser and then type:

```
. "$env:USERPROFILE\Downloads\Remove-WimShortNames.ps1";
```

2) You then have to call the newly defined function by typing:
```
Remove-WimShortNames -WimFile 'C:\iso\sources\install.wim';
```

Running this function requires an elevated PowerShell session with administrative rights.

**Comment by Hammerfest** [comment]
"You first have to execute the function definition. The idea is to copy the entire function definition to the clipboard and paste it in a PowerShell window. Alternatively, you can download the .ps1 file with your browser and then type:"

Correct, i had it downloaded from the site, PowerShell treats it no different putting .ps1 on the end or not, but I did try it both ways just-in-case

All done elevated as well which still did not work, will try that first one.

**Comment by Hammerfest** [comment]
Closing for now, will circle back to this one with some edits later
