### ISSUE TITLE
Cannot uninstall Edge

### ISSUE THREAD

**Issue by AzimsTech** [cschneegans/unattend-generator#81]
[msedge_installer.log](https://github.com/user-attachments/files/17384317/msedge_installer.log)
 
**ISO:** Windows 11 Build 26100.2033 (24h2)
**Steps to reproduce:** Attempt to uninstall Edge immediately after installing Windows.

It appears that Microsoft has fully blocked the ability to uninstall the Edge browser.

**Comment by cschneegans** [comment]
Thanks. I can reproduce your findings with build 26100.1742, and the log file is almost identical to yours.

Depending on whether you use Settings or Control Panel to uninstall, the log file will contain critical lines like these:

```
Parent process: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Stable is not uninstallable for process.
```

```
Parent process: C:\Windows\SysWOW64\dllhost.exe
Stable is not uninstallable for process.
```

```
Parent process: C:\Windows\System32\sihost.exe
Stable is not uninstallable for process.
```

The Edge uninstaller has always checked its parent process. In particular, when you call the `"C:\Program Files (x86)\Microsoft\Edge\Application\129.0.2792.89\Installer\setup.exe" --uninstall --msedge --channel=stable --system-level --verbose-logging` command directly, you will see these lines in the log file:

```
Parent process: C:\Windows\System32\cmd.exe
Stable is not uninstallable for process.
```

While earlier builds would allow e.g. **sihost.exe** to uninstall Edge, this is no longer the case. I wonder if there are still processes that are allowed to uninstall Edge – maybe some internal Microsoft tools?

This development is unfortunate, but I am afraid there is nothing I can do about it at this time.

**Comment by kzshantonu** [comment]
This script from privacy.sexy removes edge. You might want to take a look:

https://gist.mni.li/zer0/5443d99d76684c3f945e627fb632cc80

**Comment by cschneegans** [comment]
> https://gist.mni.li/zer0/5443d99d76684c3f945e627fb632cc80

That's 165 KiB (!) of hard-to-read code, and I just don't feel comfortable including it.

**Comment by AzimsTech** [comment]
My solution for now is to use the old **Win11_23H2_English_x64v2.iso,** uninstall the Edge browser, and then perform an in-place upgrade.

**Comment by Jodelmax** [comment]
Hi guys, I would like to let you know that editing the IntegratedServicesRegionPolicySet.json file is breaking Windows Update on Windows 11 24H2.

The cumulative updates (2024-11 maybe also earlier) can not be installed and throwing a 0x80070306 error.

**Comment by AzimsTech** [comment]
@Jodelmax Keep in mind that the release ISO of Windows 11 24h2 comes with sfc /scannow WebView2 bug. Maybe that's what's causing it to fail.

**Comment by cschneegans** [comment]
> Hi guys, I would like to let you know that editing the IntegratedServicesRegionPolicySet.json file is breaking Windows Update on Windows 11 24H2.

When trying to install [KB5046617](https://support.microsoft.com/en-us/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b) on a VM, I got the 0x80070306 error once. However, the installation succeeded the second time, Afterwards, Windows reports its version as 10.0.26100.2314. `IntegratedServicesRegionPolicySet.json` was reset to its original state, but this is expected.
