### ISSUE TITLE
Autounattend.xml doesn't work (fully) on latest Windows version

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [cschneegans/unattend-generator#83]
On Windows 11, OS Build 26100.2033. Some (I'll guess I'll call) settings passes do not work. The only thing I can verify that still works is automatically partitioning the disk.

**Comment by cschneegans** [comment]
> The only thing I can verify that still works is automatically partitioning the disk.

Chances are there is another autounattend.xml file somewhere that is higher up in the [search order](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-automation-overview?view=windows-11#implicit-answer-file-search-order).

Windows 11 24H2 did indeed switch to the newer “ConX” setup mode, but autounattend.xml files generated by my service are fully compatible with it.

**Comment by ShadowCodeX-debug** [comment]
I did use Rufus and I didn't bother looking at what customizations were selected.

**Comment by ShadowCodeX-debug** [comment]
Where does Rufus place its customizations?

**Comment by cschneegans** [comment]
> Where does Rufus place its customizations?

Sorry, I don't use Rufus. [Its source code](https://github.com/pbatard/rufus/blob/master/src/wue.c) seems to indicate that an `autounattend.xml` file is placed inside the `boot.wim` image. In this case, the `autounattend.xml` file is not immediately visible on your USB thumb drive, but will still be used by Windows Setup.

**Comment by icristi2** [comment]
> I did use Rufus and I didn't bother looking at what customizations were selected.

When you select to create bootable drive with Rufus the app also present you some options to customize Windows installation. This reflects in the Rufus app also creating an autounattended.xml file in the end that conflicts with the one generated by _cschneegans_ service.
By default Rufus has the following ticked:
- Remove requirement for 4GB+ RAM, Secure Boot and TPM2.0
- Remove requirement for an online Microsoft account

So my advice wold be to use _https://schneegans.de/windows/unattend-generator/_ to cover these two above options, and untick them from Rufus when creating your bootable Windows drive.


![Rufus-Windows_User_Experience_Options](https://github.com/user-attachments/assets/8e30b279-a883-4a11-9344-340aaeb72203)
