### ISSUE TITLE
REQUEST - Change TEMP folder path (Environment Variables)

### ISSUE THREAD

**Issue by saberkovich** [cschneegans/unattend-generator#84]
![image](https://github.com/user-attachments/assets/90ad2a5c-ecb8-427b-9e79-d9164178075e)

**Comment by cschneegans** [comment]
You can use custom scripts to call `setx.exe`. [This link](https://schneegans.de/windows/unattend-generator/?FirstLogonScript0=setx.exe%20TEMP%20C%3A%5CTEMP%0D%0Asetx.exe%20TMP%20C%3A%5CTEMP&FirstLogonScriptType0=Cmd&SystemScript0=mkdir%20C%3A%5CTEMP%0D%0Asetx.exe%20TEMP%20C%3A%5CTEMP%20%2FM%0D%0Asetx.exe%20TMP%20C%3A%5CTEMP%20%2FM&SystemScriptType0=Cmd&PasswordExpirationMode=Default) will configure the form accordingly. Note that one script is added to the **Scripts to run in the system context, before user accounts are created** section, and one to the **Scripts to run when the first user logs on after Windows has been installed** section.

**Comment by saberkovich** [comment]
> You can use custom scripts to call `setx.exe`. [This link](https://schneegans.de/windows/unattend-generator/?FirstLogonScript0=setx.exe%20TEMP%20C%3A%5CTEMP%0D%0Asetx.exe%20TMP%20C%3A%5CTEMP&FirstLogonScriptType0=Cmd&SystemScript0=mkdir%20C%3A%5CTEMP%0D%0Asetx.exe%20TEMP%20C%3A%5CTEMP%20%2FM%0D%0Asetx.exe%20TMP%20C%3A%5CTEMP%20%2FM&SystemScriptType0=Cmd&PasswordExpirationMode=Default) will configure the form accordingly. Note that one script is added to the **Scripts to run in the system context, before user accounts are created** section, and one to the **Scripts to run when the first user logs on after Windows has been installed** section.

Okay, thanks!
