### ISSUE TITLE
[ISSUE] [24H2] Autounattend.xml do not complete installation through desktop without user interaction

### ISSUE THREAD

**Issue by Yumekonoi** [cschneegans/unattend-generator#88]
Hi!
I'm trying to do an unattend installation with the 24H2 iso. I tested it on 23H2 and it works fine but on the 24H2 the installation stops and ask for language etc.
I saw that for work fine it must use the old setup but I cannot make it work. Maybe (probalbly :c ) I'm using it wrong...
I tried to:
- Put the code on WINPE on the first raws --> nothing;
- Put the code in the end of WINPE --> nothing but asked me to put Windows Product Key;
- Pute the code as first synchronous operation before the other and changing the number of sequence of the other ones --> nothing.

Here is the xml code (i link it because it do not show well) :
https://www.reddit.com/r/sysadmin/comments/1fwnnyg/windows_11_24h2_setup_error_with_sysprepd_image/

Thank you for your work!

**Comment by Yumekonoi** [comment]
<component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
    <RunSynchronous>
        
        <RunSynchronousCommand wcm:action="add">
            <Description>Switch to Legacy Setup</Description>
            <Order>1</Order>
            <Path>cmd /c reg add "HKLM\SYSTEM\Setup" /v CmdLine /t REG_SZ /d "X:\sources\setup.exe" /f</Path>
        </RunSynchronousCommand>
    </RunSynchronous>
</component>

**Comment by cschneegans** [comment]
autounattend.xml files generated by my service work properly with the new “ConX” setup mode that 24H2 uses by default, and I still don't understand why so many users feel the need to switch to legacy mode.

Having said that, if you really need to switch to legacy mode, see [these instructions](https://github.com/cschneegans/unattend-generator/issues/67#issuecomment-2398345559). I have not found a way to automate this. I am aware of [a post by user garlin](https://www.elevenforum.com/t/w11-24h2-and-old-installation-setup.25706/post-476942) who suggests to add
```
<RunSynchronousCommand wcm:action="add">
	<Description>Switch to legacy Setup</Description>
	<Order>1</Order>
	<Path>reg add "HKEY_LOCAL_MACHINE\SYSTEM\Setup" /v CmdLine /t REG_SZ /d "X:\sources\setup.exe" /f</Path>
</RunSynchronousCommand>
```
to the windowsPE pass. I could not make this work, and I don't even see how this is supposed to work: Adding a registry value that tells Windows Setup how to lauch setup.exe seems pointless when an instance of setup.exe already runs.

**Comment by Yumekonoi** [comment]
Hi! Thank you so much for you reply.
I don't "need" it but with your xml the installation stops and ask for language etc and do not keep the adjustments that you select on the site (like user, deleted apps etc), for this reason i searched a way to make it work. Is something that maybe i'm doing wrong? Even if the same xml works fine on the 23H2?

**Comment by cschneegans** [comment]
Chances are there is another autounattend.xml file somewhere that is higher up in the [search order](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-automation-overview?view=windows-11#implicit-answer-file-search-order). Tools like Rufus or Ventoy are known to insert their own autounattend.xml files into the Windows setup files.

**Comment by Yumekonoi** [comment]
> Chances are there is another autounattend.xml file somewhere that is higher up in the [search order](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-automation-overview?view=windows-11#implicit-answer-file-search-order). Tools like Rufus or Ventoy are known to insert their own autounattend.xml files into the Windows setup files.

Thank you so much! I did not know about Ventoy and i tried with the injection plugin method and it worked! 
In case someone see this and need to know how to do this (just for the unattend.xml file):
- Download Ventoy and install it in a +8GB USB stick;
- After install it, create two folders: ISO and Templates. In iso insert the windows iso and on templates insert the zip file with the unattend.xml file inside;
- Use the Plugin executable and insert the unattend.zip into the section "Injection Plugin";
- Insert the usb on the PC an let the install finish :)
