### ISSUE TITLE
Save states / load file to edit (feature request)

### ISSUE THREAD

**Issue by MrMarvel** [cschneegans/unattend-generator#9]
I want to edit previously created autounattend.xml on this website.
So I think it can be done when you (1) load it from file or (2) choose saved on site or (3) paste special code that is serialized data of forms (I think it's easiest way to make it possible) (like factorio blueprints codes)

**Comment by cschneegans** [comment]
autounattend.xml files created by [my service](https://schneegans.de/windows/unattend-generator/) always contain an XML comment with a URL that encodes the entire state of the form:

```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
  <!--https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&…-->
  <settings pass="offlineServicing">
```

This URL can be used to easily modify a file created previously. You can also retrieve this URL by clicking the _Bookmark selection_ button at the bottom of the page.

**Comment by MrMarvel** [comment]
Thanks I got it

> autounattend.xml files created by [my service](https://schneegans.de/windows/unattend-generator/) always contain an XML comment with a URL that encodes the entire state of the form:
