### ISSUE TITLE
Please Don't Do This...

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [cschneegans/unattend-generator#90]
Having your selected field **SWITCH** to the other field just because you have both fields have the same name is a problem since if you wanted to give your Computer Name like "ExampleName2" and you have your user name set to "ExampleName", as soon as you type in "ExampleName" it WILL switch to your user name field.

Can you just not have that happen?

https://github.com/user-attachments/assets/b09ed66c-243d-4d68-964b-1674dc9132c9

**Comment by Reptaiin** [comment]
NetBIOS and general network applications become confused when you do this, hence the restriction. While it is technically possible, it will cause problems in the long run.

**Comment by cschneegans** [comment]
That wasn't supposed to happen. Thank you for bringing this to my attention!

Changed some JavaScript code to avoid this problem. Refresh the form (F5) if you want to give it a try.

**Comment by ShadowCodeX-debug** [comment]
Thank you for solving it.
