### ISSUE TITLE
Windows 11 Enterprise 24H2 audit mode setting

### ISSUE THREAD

**Issue by DavidLevineCSC** [cschneegans/unattend-generator#92]
Hello, 
Your unattend generator is one of the best I've seen, thank you for sharing it.

Is there a place to set the new install to come up in audit mode after setup complete?

If not, and the setting is to be added to the .xml afterward, where should it go?

TIA,
David

**Comment by cschneegans** [comment]
I have no experience with the Sysprep process. I guess you should use the [Generalize](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-deployment-generalize) or and [Reseal](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-deployment-reseal) elements in your autounattend.xml file.

**Comment by DavidLevineCSC** [comment]
Thank you so much Christoph. Since 24H2 released none of my prior autounattend.xml have worked properly. The one created from your  generator was the first success. As you must know, there are several of these generators out there, but yours seems to offer many more options and settings than any of the others. 
Are you recommending to add the Reseal elements manually to the xml file?

**Comment by cschneegans** [comment]
> Are you recommending to add the Reseal elements manually to the xml file?

Checking one or more configuration passes here will create the necessary `component` elements:

![image](https://github.com/user-attachments/assets/ba184109-febd-4f36-8325-8174bece4689)

```
<component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
    <!--Placeholder-->
</component>
```

Refer to the [Reseal documentation](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-deployment-reseal) to determine which configuration pass is the correct one and what to put inside the `component` element.

**Comment by cschneegans** [comment]
I had [recently added](https://github.com/cschneegans/unattend-generator/commit/2f2a0d31e7fab99a869b56c9a168834a7f381720) the generic **Enterprise** key and have [now added](https://github.com/cschneegans/unattend-generator/commit/2878cf28006afdf36fa342fd2f579f4184f25a0e) the generic **Enterprise N** key. Both keys work with the publicly available Windows 11 .iso images such as `Win11_24H2_English_x64.iso`.

Unfortunately, product keys for **Enterprise LTSC**, **Enterprise N LTSC** or **IoT Enterprise LTSC** do not work with the publicly available Windows 11 .iso images. Therefore, I do not want to add the generic keys for these editions to the dropdown menu.

However, you can now specify your own product key directly:

![image](https://github.com/user-attachments/assets/2e316271-dca8-4742-b380-3fd8b4b45890)

You should obviously only enter generic keys there, not your private ones.
