### ISSUE TITLE
[REQUEST] Modify individual service startup option

### ISSUE THREAD

**Issue by BluSpaghetti** [cschneegans/unattend-generator#94]
Probably straight forward idk.
Could be useful to some users that usually change various services startup behaviour.

**Comment by cschneegans** [comment]
That should probably be done using a custom script with `Set-Service` (.ps1) or `sc.exe` (.cmd) calls.

**Comment by BluSpaghetti** [comment]
ok, understable.
Should the script run after the first user logs on after Windows has been installed? I'm not sure it can work before that

**Comment by cschneegans** [comment]
If the services you want to modify use built-in logons like **Local System**, **Local Service** or **Network Service**, it is probably best to create the script in the _Scripts to run in the system context, before user accounts are created_ section.

![image](https://github.com/user-attachments/assets/89175e77-643d-403b-8c0a-0e5deec620f6)
