### ISSUE TITLE
windows to go

### ISSUE THREAD

**Issue by Barmem** [cschneegans/unattend-generator#95]
is there a way to use it with windows to go?

**Comment by cschneegans** [comment]
I have no experience with Windows To Go. Articles [like this one](https://www.deploymentresearch.com/back-to-basics-automating-the-windows-to-go-setup-windows-8-1-enterprise/) let me assume that Windows To Go does indeed support autounattend.xml files, but given that fact that Windows To Go has been discontinued I don't think this is a worthwhile endeavor.
