### ISSUE TITLE
I can't get rid of “Microsoft.outlookForWindows” in taskbar

### ISSUE THREAD

**Issue by Victory61** [cschneegans/unattend-generator#96]
I cannot remove "Microsoft.outlookForWindows ” in the taskbar. 
The strange thing is that in the taskbar path the shortcut is not displayed. 
I assume the icon is generated with the network connection.
Any ideas?
Thanks

![Immagine 2024-10-30 143000](https://github.com/user-attachments/assets/82ff3333-daec-4ecc-9a89-38ef55edae13)

**Comment by cschneegans** [comment]
Use the **Delete preset icons from the taskbar** to remove the Outlook icon:

![image](https://github.com/user-attachments/assets/2f2ced7c-f4f5-4c6f-b528-d656912b7e36)

Note that taskbar icons in Windows 11 are controlled by the `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband]` registry key, not by shortcuts in the `%APPDATA%\Microsoft\Internet Explorer\Quick Launch` directory.

**Comment by Victory61** [comment]
I used the option, but unfortunately it also deletes explorer and edge icons, is there no way to delete only Outlook (new)?
Thanks

![Immagine 2024-10-30 223219](https://github.com/user-attachments/assets/50c60d6d-966d-4bcc-85cc-535590e0fb9b)

**Comment by cschneegans** [comment]
Unfortunately, the values in `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband]` use binary data to store the taskbar icons. I don't know how to selectively remove the icon for Outlook while keeping the other icons.

```
PS C:\> Get-Item -LiteralPath 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'

    Hive: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer

Name                           Property
----                           --------
Taskband                       FavoritesResolve : {62, 3, 0, 0...}
                               Favorites        : {0, 168, 1, 0...}
                               FavoritesChanges : 7
                               FavoritesVersion : 3
```

![image](https://github.com/user-attachments/assets/b25534cc-491c-4716-a421-572ac1d3bac4)

**Comment by Victory61** [comment]
Trying to experiment if it is possible to restore file explorer and d Edge icons in post installation via RunOnceEx.

**Comment by Victory61** [comment]
I tried without success.
I ran the “Delete preset icons from taskbar” option, and then restored the icons and Taskband registry key related to Explorer and Edge via RunOnceEx works only for a moment, then they disappeared again.

**Comment by Victory61** [comment]
I was able to solve with a mixed procedure.
1- Delete the preset icons in the taskbar.
2- Inserted the Taskband registry key (related only to Explorer and Edge icons) in the “Scripts to run whenever a user logs in for the first time” section.
3- In the RunOnceEx procedure, I entered the batch command that copies the Explorer and Egge icons to the taskbar.

Taskband.reg
https://justpaste.it/ei3bq

**Comment by cschneegans** [comment]
https://github.com/cschneegans/unattend-generator/issues/139 now offers a very simple solution.
