### ISSUE TITLE
Resulting  XML is not working when applied using DISM

### ISSUE THREAD

**Issue by eugenesan** [cschneegans/unattend-generator#97]
I was trying to utilize generated XML for manual DISM install but it didn't work.
Image application went without any errors but none of the embedded commands did run during subsequent reboots and resulting install seems to be missing any customization.

I wonder if that is something we can be fix?

According to documentation it should work:
[DISM Unattended Servicing Command-Line Options](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-unattended-servicing-command-line-options?view=windows-11)

This the command I've used: `dism /Apply-Image /ImageFile:d:\sources\install.wim /Index:6 /ApplyDir:w:\ /Apply-Unattend:d:\autounattend.xml`

P.S.
This use-case is the only way to install Windows on USB (due to Setup limitations) without resorting to imaging already configured installation (using WinToGo or 3rd party tools) which will always create a much more bloated system.

**Comment by cschneegans** [comment]
I am not familiar with the `DISM.exe /Image:… /Apply-Unattend:…` process.

From the page you linked: “When you use DISM to apply an unattend.xml answer file to an image, the unattended settings in the **offlineServicing** configuration pass are applied to the Windows image.” However, autounattend.xml files generated by my service do not contain any settings in the **offlineServicing** pass and will thus contain an empty `<settings pass="offlineServicing"/>` element.

**Comment by eugenesan** [comment]
Got it.
Seems like DISM works only for offlineServicing stage.
Will look for a different solution.
Thanks.
