### ISSUE TITLE
[Suggestion] Hide PowerShell windows that popup after Windows is installed.

### ISSUE THREAD

**Issue by CrPO4** [cschneegans/unattend-generator#98]
Hi!

There's something I'd like it to suggest.
After user logs in, there is a chance that you have something running, for example, language pack installations or something.
My suggestion is to make those windows appear as an icon in system tray, or even completely hidden.
This way, it'll be less intrusive for a user if running process takes some time.
As an additional "feature" of this "feature" maybe have it behave like Notepad or Excel, making it "impossible" to reboot until some modal window is not closed.
Since Powershell is able to utilize some of the C# stuff, I believe this should be doable, I'm no expert though.

Anyway, thank you very much for this useful tool, it is a game changer and makes Windows a better OS.

**Comment by cschneegans** [comment]
UserOnce.ps1 can very well contain `Read-Host` calls that prompt for user input. Hence, the PowerShell window must not be hidden.

However, I have now added a simple progress indicator, together with a note to not close the window:

![image](https://github.com/user-attachments/assets/a9c94f46-0f0b-4c03-80cb-c31c6669f899)

**Comment by CrPO4** [comment]
@cschneegans 
You are correct, in case of interactive that would case some issues.
Thanks for the new tooltip though, this seems really handy!
