### ISSUE TITLE
please, give a option to hide windows popup during Windows instalation...

### ISSUE THREAD

**Issue by FaLL3N-ighT** [cschneegans/unattend-generator#99]
Heloo ! its not realy a issue...or maybe just for my eyes :-P , please give option to hide these windows popup during Windows instalation ? thank you, I appreciate your work...

**Comment by cschneegans** [comment]
The windows are visible for the following reasons:

- Custom scripts can very well contain `Read-Host` calls that prompt for user input. These windows must not be hidden or the setup process would stall.
- Several PowerShell script (including those used to remove bloatware and [UserOnce.ps1](https://github.com/cschneegans/unattend-generator/issues/98)) make use of a visible progress bar. These should obviously not be hidden.
- PowerShell error messages are rendered using a red font. While users won't be able to read the message, they may very well register that some error occurred and then check the logs.
- Windows popping up might be somewhat distracting, but they clearly indicate that the Windows setup process is still running and has not stalled.

**Comment by cschneegans** [comment]
As a side note, https://github.com/cschneegans/unattend-generator/commit/499f40f92fcded1c4dbcabfd8f34e624305ff687 significantly reduces the number of windows popping up in the Windows PE phase of Windows Setup by combining several `echo` calls into a single line. This affects [`X:\defender.vbs`](https://github.com/cschneegans/unattend-generator/blob/master/resource/disable-defender.vbs) and `X:\diskpart.txt`.
